// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: api.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchMediaListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Sort          []string               `protobuf:"bytes,3,rep,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMediaListRequest) Reset() {
	*x = FetchMediaListRequest{}
	mi := &file_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMediaListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMediaListRequest) ProtoMessage() {}

func (x *FetchMediaListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMediaListRequest.ProtoReflect.Descriptor instead.
func (*FetchMediaListRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *FetchMediaListRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FetchMediaListRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FetchMediaListRequest) GetSort() []string {
	if x != nil {
		return x.Sort
	}
	return nil
}

type FetchMediaListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    *MediaListCollection   `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMediaListResponse) Reset() {
	*x = FetchMediaListResponse{}
	mi := &file_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMediaListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMediaListResponse) ProtoMessage() {}

func (x *FetchMediaListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMediaListResponse.ProtoReflect.Descriptor instead.
func (*FetchMediaListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *FetchMediaListResponse) GetCollection() *MediaListCollection {
	if x != nil {
		return x.Collection
	}
	return nil
}

func (x *FetchMediaListResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FetchViewerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Viewer        *Viewer                `protobuf:"bytes,1,opt,name=viewer,proto3" json:"viewer,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchViewerResponse) Reset() {
	*x = FetchViewerResponse{}
	mi := &file_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchViewerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchViewerResponse) ProtoMessage() {}

func (x *FetchViewerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchViewerResponse.ProtoReflect.Descriptor instead.
func (*FetchViewerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *FetchViewerResponse) GetViewer() *Viewer {
	if x != nil {
		return x.Viewer
	}
	return nil
}

func (x *FetchViewerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FuzzyDateInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          *int32                 `protobuf:"varint,1,opt,name=year,proto3,oneof" json:"year,omitempty"`
	Month         *int32                 `protobuf:"varint,2,opt,name=month,proto3,oneof" json:"month,omitempty"`
	Day           *int32                 `protobuf:"varint,3,opt,name=day,proto3,oneof" json:"day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FuzzyDateInput) Reset() {
	*x = FuzzyDateInput{}
	mi := &file_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FuzzyDateInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuzzyDateInput) ProtoMessage() {}

func (x *FuzzyDateInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuzzyDateInput.ProtoReflect.Descriptor instead.
func (*FuzzyDateInput) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

func (x *FuzzyDateInput) GetYear() int32 {
	if x != nil && x.Year != nil {
		return *x.Year
	}
	return 0
}

func (x *FuzzyDateInput) GetMonth() int32 {
	if x != nil && x.Month != nil {
		return *x.Month
	}
	return 0
}

func (x *FuzzyDateInput) GetDay() int32 {
	if x != nil && x.Day != nil {
		return *x.Day
	}
	return 0
}

type SaveMediaListEntryRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MediaId         int32                  `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Progress        *int32                 `protobuf:"varint,2,opt,name=progress,proto3,oneof" json:"progress,omitempty"`
	Status          *string                `protobuf:"bytes,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Score           *float64               `protobuf:"fixed64,4,opt,name=score,proto3,oneof" json:"score,omitempty"`
	StartedAt       *FuzzyDateInput        `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3,oneof" json:"started_at,omitempty"`
	CompletedAt     *FuzzyDateInput        `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	ProgressVolumes *int32                 `protobuf:"varint,7,opt,name=progress_volumes,json=progressVolumes,proto3,oneof" json:"progress_volumes,omitempty"`
	Repeat          *int32                 `protobuf:"varint,8,opt,name=repeat,proto3,oneof" json:"repeat,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SaveMediaListEntryRequest) Reset() {
	*x = SaveMediaListEntryRequest{}
	mi := &file_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveMediaListEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMediaListEntryRequest) ProtoMessage() {}

func (x *SaveMediaListEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMediaListEntryRequest.ProtoReflect.Descriptor instead.
func (*SaveMediaListEntryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *SaveMediaListEntryRequest) GetMediaId() int32 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *SaveMediaListEntryRequest) GetProgress() int32 {
	if x != nil && x.Progress != nil {
		return *x.Progress
	}
	return 0
}

func (x *SaveMediaListEntryRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *SaveMediaListEntryRequest) GetScore() float64 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

func (x *SaveMediaListEntryRequest) GetStartedAt() *FuzzyDateInput {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *SaveMediaListEntryRequest) GetCompletedAt() *FuzzyDateInput {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *SaveMediaListEntryRequest) GetProgressVolumes() int32 {
	if x != nil && x.ProgressVolumes != nil {
		return *x.ProgressVolumes
	}
	return 0
}

func (x *SaveMediaListEntryRequest) GetRepeat() int32 {
	if x != nil && x.Repeat != nil {
		return *x.Repeat
	}
	return 0
}

type SaveMediaListEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *MediaListEntry        `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveMediaListEntryResponse) Reset() {
	*x = SaveMediaListEntryResponse{}
	mi := &file_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveMediaListEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMediaListEntryResponse) ProtoMessage() {}

func (x *SaveMediaListEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMediaListEntryResponse.ProtoReflect.Descriptor instead.
func (*SaveMediaListEntryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *SaveMediaListEntryResponse) GetEntry() *MediaListEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *SaveMediaListEntryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FetchMediaDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       int32                  `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMediaDetailsRequest) Reset() {
	*x = FetchMediaDetailsRequest{}
	mi := &file_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMediaDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMediaDetailsRequest) ProtoMessage() {}

func (x *FetchMediaDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMediaDetailsRequest.ProtoReflect.Descriptor instead.
func (*FetchMediaDetailsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *FetchMediaDetailsRequest) GetMediaId() int32 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

type FetchMediaDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *Media                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMediaDetailsResponse) Reset() {
	*x = FetchMediaDetailsResponse{}
	mi := &file_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMediaDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMediaDetailsResponse) ProtoMessage() {}

func (x *FetchMediaDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMediaDetailsResponse.ProtoReflect.Descriptor instead.
func (*FetchMediaDetailsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *FetchMediaDetailsResponse) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *FetchMediaDetailsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FetchMediaStaffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       int32                  `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,3,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMediaStaffRequest) Reset() {
	*x = FetchMediaStaffRequest{}
	mi := &file_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMediaStaffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMediaStaffRequest) ProtoMessage() {}

func (x *FetchMediaStaffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMediaStaffRequest.ProtoReflect.Descriptor instead.
func (*FetchMediaStaffRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

func (x *FetchMediaStaffRequest) GetMediaId() int32 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *FetchMediaStaffRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FetchMediaStaffRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type FetchMediaStaffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *Media                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMediaStaffResponse) Reset() {
	*x = FetchMediaStaffResponse{}
	mi := &file_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMediaStaffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMediaStaffResponse) ProtoMessage() {}

func (x *FetchMediaStaffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMediaStaffResponse.ProtoReflect.Descriptor instead.
func (*FetchMediaStaffResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *FetchMediaStaffResponse) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *FetchMediaStaffResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FetchMediaCharactersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       int32                  `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,3,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMediaCharactersRequest) Reset() {
	*x = FetchMediaCharactersRequest{}
	mi := &file_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMediaCharactersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMediaCharactersRequest) ProtoMessage() {}

func (x *FetchMediaCharactersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMediaCharactersRequest.ProtoReflect.Descriptor instead.
func (*FetchMediaCharactersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

func (x *FetchMediaCharactersRequest) GetMediaId() int32 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *FetchMediaCharactersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FetchMediaCharactersRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type FetchMediaCharactersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *Media                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMediaCharactersResponse) Reset() {
	*x = FetchMediaCharactersResponse{}
	mi := &file_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMediaCharactersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMediaCharactersResponse) ProtoMessage() {}

func (x *FetchMediaCharactersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMediaCharactersResponse.ProtoReflect.Descriptor instead.
func (*FetchMediaCharactersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *FetchMediaCharactersResponse) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *FetchMediaCharactersResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FetchMediaRecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       int32                  `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,3,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMediaRecommendationsRequest) Reset() {
	*x = FetchMediaRecommendationsRequest{}
	mi := &file_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMediaRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMediaRecommendationsRequest) ProtoMessage() {}

func (x *FetchMediaRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMediaRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*FetchMediaRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

func (x *FetchMediaRecommendationsRequest) GetMediaId() int32 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *FetchMediaRecommendationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FetchMediaRecommendationsRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type FetchMediaRecommendationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *Media                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMediaRecommendationsResponse) Reset() {
	*x = FetchMediaRecommendationsResponse{}
	mi := &file_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMediaRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMediaRecommendationsResponse) ProtoMessage() {}

func (x *FetchMediaRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMediaRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*FetchMediaRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{13}
}

func (x *FetchMediaRecommendationsResponse) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *FetchMediaRecommendationsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ToggleFavouriteAnimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnimeId       int32                  `protobuf:"varint,1,opt,name=anime_id,json=animeId,proto3" json:"anime_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleFavouriteAnimeRequest) Reset() {
	*x = ToggleFavouriteAnimeRequest{}
	mi := &file_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleFavouriteAnimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleFavouriteAnimeRequest) ProtoMessage() {}

func (x *ToggleFavouriteAnimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleFavouriteAnimeRequest.ProtoReflect.Descriptor instead.
func (*ToggleFavouriteAnimeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{14}
}

func (x *ToggleFavouriteAnimeRequest) GetAnimeId() int32 {
	if x != nil {
		return x.AnimeId
	}
	return 0
}

type ToggleFavouriteAnimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnimeId       int32                  `protobuf:"varint,1,opt,name=anime_id,json=animeId,proto3" json:"anime_id,omitempty"`
	IsFavourite   bool                   `protobuf:"varint,2,opt,name=is_favourite,json=isFavourite,proto3" json:"is_favourite,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleFavouriteAnimeResponse) Reset() {
	*x = ToggleFavouriteAnimeResponse{}
	mi := &file_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleFavouriteAnimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleFavouriteAnimeResponse) ProtoMessage() {}

func (x *ToggleFavouriteAnimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleFavouriteAnimeResponse.ProtoReflect.Descriptor instead.
func (*ToggleFavouriteAnimeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{15}
}

func (x *ToggleFavouriteAnimeResponse) GetAnimeId() int32 {
	if x != nil {
		return x.AnimeId
	}
	return 0
}

func (x *ToggleFavouriteAnimeResponse) GetIsFavourite() bool {
	if x != nil {
		return x.IsFavourite
	}
	return false
}

func (x *ToggleFavouriteAnimeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ToggleFavouriteMangaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MangaId       int32                  `protobuf:"varint,1,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleFavouriteMangaRequest) Reset() {
	*x = ToggleFavouriteMangaRequest{}
	mi := &file_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleFavouriteMangaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleFavouriteMangaRequest) ProtoMessage() {}

func (x *ToggleFavouriteMangaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleFavouriteMangaRequest.ProtoReflect.Descriptor instead.
func (*ToggleFavouriteMangaRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{16}
}

func (x *ToggleFavouriteMangaRequest) GetMangaId() int32 {
	if x != nil {
		return x.MangaId
	}
	return 0
}

type ToggleFavouriteMangaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MangaId       int32                  `protobuf:"varint,1,opt,name=manga_id,json=mangaId,proto3" json:"manga_id,omitempty"`
	IsFavourite   bool                   `protobuf:"varint,2,opt,name=is_favourite,json=isFavourite,proto3" json:"is_favourite,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleFavouriteMangaResponse) Reset() {
	*x = ToggleFavouriteMangaResponse{}
	mi := &file_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleFavouriteMangaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleFavouriteMangaResponse) ProtoMessage() {}

func (x *ToggleFavouriteMangaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleFavouriteMangaResponse.ProtoReflect.Descriptor instead.
func (*ToggleFavouriteMangaResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{17}
}

func (x *ToggleFavouriteMangaResponse) GetMangaId() int32 {
	if x != nil {
		return x.MangaId
	}
	return 0
}

func (x *ToggleFavouriteMangaResponse) GetIsFavourite() bool {
	if x != nil {
		return x.IsFavourite
	}
	return false
}

func (x *ToggleFavouriteMangaResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ToggleActivityLikeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    int32                  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleActivityLikeRequest) Reset() {
	*x = ToggleActivityLikeRequest{}
	mi := &file_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleActivityLikeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleActivityLikeRequest) ProtoMessage() {}

func (x *ToggleActivityLikeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleActivityLikeRequest.ProtoReflect.Descriptor instead.
func (*ToggleActivityLikeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{18}
}

func (x *ToggleActivityLikeRequest) GetActivityId() int32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type ToggleActivityLikeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActivityId    int32                  `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	LikedUserIds  []int32                `protobuf:"varint,2,rep,packed,name=liked_user_ids,json=likedUserIds,proto3" json:"liked_user_ids,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleActivityLikeResponse) Reset() {
	*x = ToggleActivityLikeResponse{}
	mi := &file_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleActivityLikeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleActivityLikeResponse) ProtoMessage() {}

func (x *ToggleActivityLikeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleActivityLikeResponse.ProtoReflect.Descriptor instead.
func (*ToggleActivityLikeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{19}
}

func (x *ToggleActivityLikeResponse) GetActivityId() int32 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *ToggleActivityLikeResponse) GetLikedUserIds() []int32 {
	if x != nil {
		return x.LikedUserIds
	}
	return nil
}

func (x *ToggleActivityLikeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DeleteMediaListEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryId       int32                  `protobuf:"varint,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMediaListEntryRequest) Reset() {
	*x = DeleteMediaListEntryRequest{}
	mi := &file_api_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaListEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaListEntryRequest) ProtoMessage() {}

func (x *DeleteMediaListEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaListEntryRequest.ProtoReflect.Descriptor instead.
func (*DeleteMediaListEntryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteMediaListEntryRequest) GetEntryId() int32 {
	if x != nil {
		return x.EntryId
	}
	return 0
}

type DeleteMediaListEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EntryId       int32                  `protobuf:"varint,1,opt,name=entry_id,json=entryId,proto3" json:"entry_id,omitempty"`
	Deleted       bool                   `protobuf:"varint,2,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMediaListEntryResponse) Reset() {
	*x = DeleteMediaListEntryResponse{}
	mi := &file_api_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMediaListEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMediaListEntryResponse) ProtoMessage() {}

func (x *DeleteMediaListEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMediaListEntryResponse.ProtoReflect.Descriptor instead.
func (*DeleteMediaListEntryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteMediaListEntryResponse) GetEntryId() int32 {
	if x != nil {
		return x.EntryId
	}
	return 0
}

func (x *DeleteMediaListEntryResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *DeleteMediaListEntryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FetchMediaReviewsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       int32                  `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,3,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMediaReviewsRequest) Reset() {
	*x = FetchMediaReviewsRequest{}
	mi := &file_api_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMediaReviewsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMediaReviewsRequest) ProtoMessage() {}

func (x *FetchMediaReviewsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMediaReviewsRequest.ProtoReflect.Descriptor instead.
func (*FetchMediaReviewsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{22}
}

func (x *FetchMediaReviewsRequest) GetMediaId() int32 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *FetchMediaReviewsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FetchMediaReviewsRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type FetchMediaReviewsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *Media                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMediaReviewsResponse) Reset() {
	*x = FetchMediaReviewsResponse{}
	mi := &file_api_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMediaReviewsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMediaReviewsResponse) ProtoMessage() {}

func (x *FetchMediaReviewsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMediaReviewsResponse.ProtoReflect.Descriptor instead.
func (*FetchMediaReviewsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{23}
}

func (x *FetchMediaReviewsResponse) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *FetchMediaReviewsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RateReviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReviewId      int32                  `protobuf:"varint,1,opt,name=review_id,json=reviewId,proto3" json:"review_id,omitempty"`
	Rating        ReviewUserRating       `protobuf:"varint,2,opt,name=rating,proto3,enum=goodanime.ReviewUserRating" json:"rating,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateReviewRequest) Reset() {
	*x = RateReviewRequest{}
	mi := &file_api_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateReviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateReviewRequest) ProtoMessage() {}

func (x *RateReviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateReviewRequest.ProtoReflect.Descriptor instead.
func (*RateReviewRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{24}
}

func (x *RateReviewRequest) GetReviewId() int32 {
	if x != nil {
		return x.ReviewId
	}
	return 0
}

func (x *RateReviewRequest) GetRating() ReviewUserRating {
	if x != nil {
		return x.Rating
	}
	return ReviewUserRating_REVIEW_USER_RATING_NO_VOTE_UNSPECIFIED
}

type RateReviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Review        *ReviewNode            `protobuf:"bytes,1,opt,name=review,proto3" json:"review,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateReviewResponse) Reset() {
	*x = RateReviewResponse{}
	mi := &file_api_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateReviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateReviewResponse) ProtoMessage() {}

func (x *RateReviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateReviewResponse.ProtoReflect.Descriptor instead.
func (*RateReviewResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{25}
}

func (x *RateReviewResponse) GetReview() *ReviewNode {
	if x != nil {
		return x.Review
	}
	return nil
}

func (x *RateReviewResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FetchMediaActivitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       int32                  `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,3,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMediaActivitiesRequest) Reset() {
	*x = FetchMediaActivitiesRequest{}
	mi := &file_api_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMediaActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMediaActivitiesRequest) ProtoMessage() {}

func (x *FetchMediaActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMediaActivitiesRequest.ProtoReflect.Descriptor instead.
func (*FetchMediaActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{26}
}

func (x *FetchMediaActivitiesRequest) GetMediaId() int32 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *FetchMediaActivitiesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FetchMediaActivitiesRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type FetchMediaActivitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageInfo      *PageInfo              `protobuf:"bytes,1,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	Activities    []*ListActivity        `protobuf:"bytes,2,rep,name=activities,proto3" json:"activities,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMediaActivitiesResponse) Reset() {
	*x = FetchMediaActivitiesResponse{}
	mi := &file_api_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMediaActivitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMediaActivitiesResponse) ProtoMessage() {}

func (x *FetchMediaActivitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMediaActivitiesResponse.ProtoReflect.Descriptor instead.
func (*FetchMediaActivitiesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{27}
}

func (x *FetchMediaActivitiesResponse) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *FetchMediaActivitiesResponse) GetActivities() []*ListActivity {
	if x != nil {
		return x.Activities
	}
	return nil
}

func (x *FetchMediaActivitiesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_api_proto protoreflect.FileDescriptor

const file_api_proto_rawDesc = "" +
	"\n" +
	"\tapi.proto\x12\tgoodanime\x1a\fcommon.proto\x1a\vmedia.proto\x1a\x14media_activity.proto\x1a\x10media_list.proto\x1a\x16media_list_entry.proto\x1a\x12media_review.proto\x1a\fviewer.proto\"X\n" +
	"\x15FetchMediaListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04sort\x18\x03 \x03(\tR\x04sort\"n\n" +
	"\x16FetchMediaListResponse\x12>\n" +
	"\n" +
	"collection\x18\x01 \x01(\v2\x1e.goodanime.MediaListCollectionR\n" +
	"collection\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"V\n" +
	"\x13FetchViewerResponse\x12)\n" +
	"\x06viewer\x18\x01 \x01(\v2\x11.goodanime.ViewerR\x06viewer\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"v\n" +
	"\x0eFuzzyDateInput\x12\x17\n" +
	"\x04year\x18\x01 \x01(\x05H\x00R\x04year\x88\x01\x01\x12\x19\n" +
	"\x05month\x18\x02 \x01(\x05H\x01R\x05month\x88\x01\x01\x12\x15\n" +
	"\x03day\x18\x03 \x01(\x05H\x02R\x03day\x88\x01\x01B\a\n" +
	"\x05_yearB\b\n" +
	"\x06_monthB\x06\n" +
	"\x04_day\"\xc0\x03\n" +
	"\x19SaveMediaListEntryRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\x05R\amediaId\x12\x1f\n" +
	"\bprogress\x18\x02 \x01(\x05H\x00R\bprogress\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\tH\x01R\x06status\x88\x01\x01\x12\x19\n" +
	"\x05score\x18\x04 \x01(\x01H\x02R\x05score\x88\x01\x01\x12=\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x19.goodanime.FuzzyDateInputH\x03R\tstartedAt\x88\x01\x01\x12A\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x19.goodanime.FuzzyDateInputH\x04R\vcompletedAt\x88\x01\x01\x12.\n" +
	"\x10progress_volumes\x18\a \x01(\x05H\x05R\x0fprogressVolumes\x88\x01\x01\x12\x1b\n" +
	"\x06repeat\x18\b \x01(\x05H\x06R\x06repeat\x88\x01\x01B\v\n" +
	"\t_progressB\t\n" +
	"\a_statusB\b\n" +
	"\x06_scoreB\r\n" +
	"\v_started_atB\x0f\n" +
	"\r_completed_atB\x13\n" +
	"\x11_progress_volumesB\t\n" +
	"\a_repeat\"c\n" +
	"\x1aSaveMediaListEntryResponse\x12/\n" +
	"\x05entry\x18\x01 \x01(\v2\x19.goodanime.MediaListEntryR\x05entry\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"5\n" +
	"\x18FetchMediaDetailsRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\x05R\amediaId\"Y\n" +
	"\x19FetchMediaDetailsResponse\x12&\n" +
	"\x05media\x18\x01 \x01(\v2\x10.goodanime.MediaR\x05media\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"b\n" +
	"\x16FetchMediaStaffRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\x05R\amediaId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x03 \x01(\x05R\aperPage\"W\n" +
	"\x17FetchMediaStaffResponse\x12&\n" +
	"\x05media\x18\x01 \x01(\v2\x10.goodanime.MediaR\x05media\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"g\n" +
	"\x1bFetchMediaCharactersRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\x05R\amediaId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x03 \x01(\x05R\aperPage\"\\\n" +
	"\x1cFetchMediaCharactersResponse\x12&\n" +
	"\x05media\x18\x01 \x01(\v2\x10.goodanime.MediaR\x05media\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"l\n" +
	" FetchMediaRecommendationsRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\x05R\amediaId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x03 \x01(\x05R\aperPage\"a\n" +
	"!FetchMediaRecommendationsResponse\x12&\n" +
	"\x05media\x18\x01 \x01(\v2\x10.goodanime.MediaR\x05media\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"8\n" +
	"\x1bToggleFavouriteAnimeRequest\x12\x19\n" +
	"\banime_id\x18\x01 \x01(\x05R\aanimeId\"r\n" +
	"\x1cToggleFavouriteAnimeResponse\x12\x19\n" +
	"\banime_id\x18\x01 \x01(\x05R\aanimeId\x12!\n" +
	"\fis_favourite\x18\x02 \x01(\bR\visFavourite\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"8\n" +
	"\x1bToggleFavouriteMangaRequest\x12\x19\n" +
	"\bmanga_id\x18\x01 \x01(\x05R\amangaId\"r\n" +
	"\x1cToggleFavouriteMangaResponse\x12\x19\n" +
	"\bmanga_id\x18\x01 \x01(\x05R\amangaId\x12!\n" +
	"\fis_favourite\x18\x02 \x01(\bR\visFavourite\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"<\n" +
	"\x19ToggleActivityLikeRequest\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x05R\n" +
	"activityId\"y\n" +
	"\x1aToggleActivityLikeResponse\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x05R\n" +
	"activityId\x12$\n" +
	"\x0eliked_user_ids\x18\x02 \x03(\x05R\flikedUserIds\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"8\n" +
	"\x1bDeleteMediaListEntryRequest\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\x05R\aentryId\"i\n" +
	"\x1cDeleteMediaListEntryResponse\x12\x19\n" +
	"\bentry_id\x18\x01 \x01(\x05R\aentryId\x12\x18\n" +
	"\adeleted\x18\x02 \x01(\bR\adeleted\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"d\n" +
	"\x18FetchMediaReviewsRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\x05R\amediaId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x03 \x01(\x05R\aperPage\"Y\n" +
	"\x19FetchMediaReviewsResponse\x12&\n" +
	"\x05media\x18\x01 \x01(\v2\x10.goodanime.MediaR\x05media\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"e\n" +
	"\x11RateReviewRequest\x12\x1b\n" +
	"\treview_id\x18\x01 \x01(\x05R\breviewId\x123\n" +
	"\x06rating\x18\x02 \x01(\x0e2\x1b.goodanime.ReviewUserRatingR\x06rating\"Y\n" +
	"\x12RateReviewResponse\x12-\n" +
	"\x06review\x18\x01 \x01(\v2\x15.goodanime.ReviewNodeR\x06review\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"g\n" +
	"\x1bFetchMediaActivitiesRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\x05R\amediaId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x03 \x01(\x05R\aperPage\"\x9f\x01\n" +
	"\x1cFetchMediaActivitiesResponse\x120\n" +
	"\tpage_info\x18\x01 \x01(\v2\x13.goodanime.PageInfoR\bpageInfo\x127\n" +
	"\n" +
	"activities\x18\x02 \x03(\v2\x17.goodanime.ListActivityR\n" +
	"activities\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05errorB\x19Z\x17goodanime/backend/protob\x06proto3"

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData []byte
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)))
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_api_proto_goTypes = []any{
	(*FetchMediaListRequest)(nil),             // 0: goodanime.FetchMediaListRequest
	(*FetchMediaListResponse)(nil),            // 1: goodanime.FetchMediaListResponse
	(*FetchViewerResponse)(nil),               // 2: goodanime.FetchViewerResponse
	(*FuzzyDateInput)(nil),                    // 3: goodanime.FuzzyDateInput
	(*SaveMediaListEntryRequest)(nil),         // 4: goodanime.SaveMediaListEntryRequest
	(*SaveMediaListEntryResponse)(nil),        // 5: goodanime.SaveMediaListEntryResponse
	(*FetchMediaDetailsRequest)(nil),          // 6: goodanime.FetchMediaDetailsRequest
	(*FetchMediaDetailsResponse)(nil),         // 7: goodanime.FetchMediaDetailsResponse
	(*FetchMediaStaffRequest)(nil),            // 8: goodanime.FetchMediaStaffRequest
	(*FetchMediaStaffResponse)(nil),           // 9: goodanime.FetchMediaStaffResponse
	(*FetchMediaCharactersRequest)(nil),       // 10: goodanime.FetchMediaCharactersRequest
	(*FetchMediaCharactersResponse)(nil),      // 11: goodanime.FetchMediaCharactersResponse
	(*FetchMediaRecommendationsRequest)(nil),  // 12: goodanime.FetchMediaRecommendationsRequest
	(*FetchMediaRecommendationsResponse)(nil), // 13: goodanime.FetchMediaRecommendationsResponse
	(*ToggleFavouriteAnimeRequest)(nil),       // 14: goodanime.ToggleFavouriteAnimeRequest
	(*ToggleFavouriteAnimeResponse)(nil),      // 15: goodanime.ToggleFavouriteAnimeResponse
	(*ToggleFavouriteMangaRequest)(nil),       // 16: goodanime.ToggleFavouriteMangaRequest
	(*ToggleFavouriteMangaResponse)(nil),      // 17: goodanime.ToggleFavouriteMangaResponse
	(*ToggleActivityLikeRequest)(nil),         // 18: goodanime.ToggleActivityLikeRequest
	(*ToggleActivityLikeResponse)(nil),        // 19: goodanime.ToggleActivityLikeResponse
	(*DeleteMediaListEntryRequest)(nil),       // 20: goodanime.DeleteMediaListEntryRequest
	(*DeleteMediaListEntryResponse)(nil),      // 21: goodanime.DeleteMediaListEntryResponse
	(*FetchMediaReviewsRequest)(nil),          // 22: goodanime.FetchMediaReviewsRequest
	(*FetchMediaReviewsResponse)(nil),         // 23: goodanime.FetchMediaReviewsResponse
	(*RateReviewRequest)(nil),                 // 24: goodanime.RateReviewRequest
	(*RateReviewResponse)(nil),                // 25: goodanime.RateReviewResponse
	(*FetchMediaActivitiesRequest)(nil),       // 26: goodanime.FetchMediaActivitiesRequest
	(*FetchMediaActivitiesResponse)(nil),      // 27: goodanime.FetchMediaActivitiesResponse
	(*MediaListCollection)(nil),               // 28: goodanime.MediaListCollection
	(*Viewer)(nil),                            // 29: goodanime.Viewer
	(*MediaListEntry)(nil),                    // 30: goodanime.MediaListEntry
	(*Media)(nil),                             // 31: goodanime.Media
	(ReviewUserRating)(0),                     // 32: goodanime.ReviewUserRating
	(*ReviewNode)(nil),                        // 33: goodanime.ReviewNode
	(*PageInfo)(nil),                          // 34: goodanime.PageInfo
	(*ListActivity)(nil),                      // 35: goodanime.ListActivity
}
var file_api_proto_depIdxs = []int32{
	28, // 0: goodanime.FetchMediaListResponse.collection:type_name -> goodanime.MediaListCollection
	29, // 1: goodanime.FetchViewerResponse.viewer:type_name -> goodanime.Viewer
	3,  // 2: goodanime.SaveMediaListEntryRequest.started_at:type_name -> goodanime.FuzzyDateInput
	3,  // 3: goodanime.SaveMediaListEntryRequest.completed_at:type_name -> goodanime.FuzzyDateInput
	30, // 4: goodanime.SaveMediaListEntryResponse.entry:type_name -> goodanime.MediaListEntry
	31, // 5: goodanime.FetchMediaDetailsResponse.media:type_name -> goodanime.Media
	31, // 6: goodanime.FetchMediaStaffResponse.media:type_name -> goodanime.Media
	31, // 7: goodanime.FetchMediaCharactersResponse.media:type_name -> goodanime.Media
	31, // 8: goodanime.FetchMediaRecommendationsResponse.media:type_name -> goodanime.Media
	31, // 9: goodanime.FetchMediaReviewsResponse.media:type_name -> goodanime.Media
	32, // 10: goodanime.RateReviewRequest.rating:type_name -> goodanime.ReviewUserRating
	33, // 11: goodanime.RateReviewResponse.review:type_name -> goodanime.ReviewNode
	34, // 12: goodanime.FetchMediaActivitiesResponse.page_info:type_name -> goodanime.PageInfo
	35, // 13: goodanime.FetchMediaActivitiesResponse.activities:type_name -> goodanime.ListActivity
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	file_common_proto_init()
	file_media_proto_init()
	file_media_activity_proto_init()
	file_media_list_proto_init()
	file_media_list_entry_proto_init()
	file_media_review_proto_init()
	file_viewer_proto_init()
	file_api_proto_msgTypes[3].OneofWrappers = []any{}
	file_api_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_rawDesc), len(file_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
