// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaListStatus int32

const (
	MediaListStatus_MEDIA_LIST_STATUS_UNSPECIFIED MediaListStatus = 0
	MediaListStatus_MEDIA_LIST_STATUS_CURRENT     MediaListStatus = 1
	MediaListStatus_MEDIA_LIST_STATUS_PLANNING    MediaListStatus = 2
	MediaListStatus_MEDIA_LIST_STATUS_COMPLETED   MediaListStatus = 3
	MediaListStatus_MEDIA_LIST_STATUS_DROPPED     MediaListStatus = 4
	MediaListStatus_MEDIA_LIST_STATUS_PAUSED      MediaListStatus = 5
	MediaListStatus_MEDIA_LIST_STATUS_REPEATING   MediaListStatus = 6
)

// Enum value maps for MediaListStatus.
var (
	MediaListStatus_name = map[int32]string{
		0: "MEDIA_LIST_STATUS_UNSPECIFIED",
		1: "MEDIA_LIST_STATUS_CURRENT",
		2: "MEDIA_LIST_STATUS_PLANNING",
		3: "MEDIA_LIST_STATUS_COMPLETED",
		4: "MEDIA_LIST_STATUS_DROPPED",
		5: "MEDIA_LIST_STATUS_PAUSED",
		6: "MEDIA_LIST_STATUS_REPEATING",
	}
	MediaListStatus_value = map[string]int32{
		"MEDIA_LIST_STATUS_UNSPECIFIED": 0,
		"MEDIA_LIST_STATUS_CURRENT":     1,
		"MEDIA_LIST_STATUS_PLANNING":    2,
		"MEDIA_LIST_STATUS_COMPLETED":   3,
		"MEDIA_LIST_STATUS_DROPPED":     4,
		"MEDIA_LIST_STATUS_PAUSED":      5,
		"MEDIA_LIST_STATUS_REPEATING":   6,
	}
)

func (x MediaListStatus) Enum() *MediaListStatus {
	p := new(MediaListStatus)
	*p = x
	return p
}

func (x MediaListStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaListStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_proto_enumTypes[0].Descriptor()
}

func (MediaListStatus) Type() protoreflect.EnumType {
	return &file_common_proto_enumTypes[0]
}

func (x MediaListStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaListStatus.Descriptor instead.
func (MediaListStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

type FuzzyDate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           *int32                 `protobuf:"varint,1,opt,name=day,proto3,oneof" json:"day,omitempty"`
	Month         *int32                 `protobuf:"varint,2,opt,name=month,proto3,oneof" json:"month,omitempty"`
	Year          *int32                 `protobuf:"varint,3,opt,name=year,proto3,oneof" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FuzzyDate) Reset() {
	*x = FuzzyDate{}
	mi := &file_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FuzzyDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuzzyDate) ProtoMessage() {}

func (x *FuzzyDate) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuzzyDate.ProtoReflect.Descriptor instead.
func (*FuzzyDate) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{0}
}

func (x *FuzzyDate) GetDay() int32 {
	if x != nil && x.Day != nil {
		return *x.Day
	}
	return 0
}

func (x *FuzzyDate) GetMonth() int32 {
	if x != nil && x.Month != nil {
		return *x.Month
	}
	return 0
}

func (x *FuzzyDate) GetYear() int32 {
	if x != nil && x.Year != nil {
		return *x.Year
	}
	return 0
}

type PageInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasNextPage   bool                   `protobuf:"varint,1,opt,name=has_next_page,json=hasNextPage,proto3" json:"has_next_page,omitempty"`
	CurrentPage   int32                  `protobuf:"varint,2,opt,name=current_page,json=currentPage,proto3" json:"current_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PageInfo) Reset() {
	*x = PageInfo{}
	mi := &file_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PageInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PageInfo) ProtoMessage() {}

func (x *PageInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PageInfo.ProtoReflect.Descriptor instead.
func (*PageInfo) Descriptor() ([]byte, []int) {
	return file_common_proto_rawDescGZIP(), []int{1}
}

func (x *PageInfo) GetHasNextPage() bool {
	if x != nil {
		return x.HasNextPage
	}
	return false
}

func (x *PageInfo) GetCurrentPage() int32 {
	if x != nil {
		return x.CurrentPage
	}
	return 0
}

var File_common_proto protoreflect.FileDescriptor

const file_common_proto_rawDesc = "" +
	"\n" +
	"\fcommon.proto\x12\tgoodanime\"q\n" +
	"\tFuzzyDate\x12\x15\n" +
	"\x03day\x18\x01 \x01(\x05H\x00R\x03day\x88\x01\x01\x12\x19\n" +
	"\x05month\x18\x02 \x01(\x05H\x01R\x05month\x88\x01\x01\x12\x17\n" +
	"\x04year\x18\x03 \x01(\x05H\x02R\x04year\x88\x01\x01B\x06\n" +
	"\x04_dayB\b\n" +
	"\x06_monthB\a\n" +
	"\x05_year\"Q\n" +
	"\bPageInfo\x12\"\n" +
	"\rhas_next_page\x18\x01 \x01(\bR\vhasNextPage\x12!\n" +
	"\fcurrent_page\x18\x02 \x01(\x05R\vcurrentPage*\xf2\x01\n" +
	"\x0fMediaListStatus\x12!\n" +
	"\x1dMEDIA_LIST_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19MEDIA_LIST_STATUS_CURRENT\x10\x01\x12\x1e\n" +
	"\x1aMEDIA_LIST_STATUS_PLANNING\x10\x02\x12\x1f\n" +
	"\x1bMEDIA_LIST_STATUS_COMPLETED\x10\x03\x12\x1d\n" +
	"\x19MEDIA_LIST_STATUS_DROPPED\x10\x04\x12\x1c\n" +
	"\x18MEDIA_LIST_STATUS_PAUSED\x10\x05\x12\x1f\n" +
	"\x1bMEDIA_LIST_STATUS_REPEATING\x10\x06B\x19Z\x17goodanime/backend/protob\x06proto3"

var (
	file_common_proto_rawDescOnce sync.Once
	file_common_proto_rawDescData []byte
)

func file_common_proto_rawDescGZIP() []byte {
	file_common_proto_rawDescOnce.Do(func() {
		file_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)))
	})
	return file_common_proto_rawDescData
}

var file_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_proto_goTypes = []any{
	(MediaListStatus)(0), // 0: goodanime.MediaListStatus
	(*FuzzyDate)(nil),    // 1: goodanime.FuzzyDate
	(*PageInfo)(nil),     // 2: goodanime.PageInfo
}
var file_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_proto_init() }
func file_common_proto_init() {
	if File_common_proto != nil {
		return
	}
	file_common_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_proto_rawDesc), len(file_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_proto_goTypes,
		DependencyIndexes: file_common_proto_depIdxs,
		EnumInfos:         file_common_proto_enumTypes,
		MessageInfos:      file_common_proto_msgTypes,
	}.Build()
	File_common_proto = out.File
	file_common_proto_goTypes = nil
	file_common_proto_depIdxs = nil
}
