// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: media_list_entry.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaListEntry struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status          *MediaListStatus       `protobuf:"varint,2,opt,name=status,proto3,enum=goodanime.MediaListStatus,oneof" json:"status,omitempty"`
	Progress        int32                  `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`
	Score           float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	Repeat          int32                  `protobuf:"varint,5,opt,name=repeat,proto3" json:"repeat,omitempty"`
	StartedAt       *FuzzyDate             `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt     *FuzzyDate             `protobuf:"bytes,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	ProgressVolumes int32                  `protobuf:"varint,8,opt,name=progress_volumes,json=progressVolumes,proto3" json:"progress_volumes,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MediaListEntry) Reset() {
	*x = MediaListEntry{}
	mi := &file_media_list_entry_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaListEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaListEntry) ProtoMessage() {}

func (x *MediaListEntry) ProtoReflect() protoreflect.Message {
	mi := &file_media_list_entry_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaListEntry.ProtoReflect.Descriptor instead.
func (*MediaListEntry) Descriptor() ([]byte, []int) {
	return file_media_list_entry_proto_rawDescGZIP(), []int{0}
}

func (x *MediaListEntry) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MediaListEntry) GetStatus() MediaListStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return MediaListStatus_MEDIA_LIST_STATUS_UNSPECIFIED
}

func (x *MediaListEntry) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *MediaListEntry) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *MediaListEntry) GetRepeat() int32 {
	if x != nil {
		return x.Repeat
	}
	return 0
}

func (x *MediaListEntry) GetStartedAt() *FuzzyDate {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *MediaListEntry) GetCompletedAt() *FuzzyDate {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *MediaListEntry) GetProgressVolumes() int32 {
	if x != nil {
		return x.ProgressVolumes
	}
	return 0
}

var File_media_list_entry_proto protoreflect.FileDescriptor

const file_media_list_entry_proto_rawDesc = "" +
	"\n" +
	"\x16media_list_entry.proto\x12\tgoodanime\x1a\fcommon.proto\"\xc7\x02\n" +
	"\x0eMediaListEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x127\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.goodanime.MediaListStatusH\x00R\x06status\x88\x01\x01\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x05R\bprogress\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12\x16\n" +
	"\x06repeat\x18\x05 \x01(\x05R\x06repeat\x123\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x14.goodanime.FuzzyDateR\tstartedAt\x127\n" +
	"\fcompleted_at\x18\a \x01(\v2\x14.goodanime.FuzzyDateR\vcompletedAt\x12)\n" +
	"\x10progress_volumes\x18\b \x01(\x05R\x0fprogressVolumesB\t\n" +
	"\a_statusB\x19Z\x17goodanime/backend/protob\x06proto3"

var (
	file_media_list_entry_proto_rawDescOnce sync.Once
	file_media_list_entry_proto_rawDescData []byte
)

func file_media_list_entry_proto_rawDescGZIP() []byte {
	file_media_list_entry_proto_rawDescOnce.Do(func() {
		file_media_list_entry_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_list_entry_proto_rawDesc), len(file_media_list_entry_proto_rawDesc)))
	})
	return file_media_list_entry_proto_rawDescData
}

var file_media_list_entry_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_media_list_entry_proto_goTypes = []any{
	(*MediaListEntry)(nil), // 0: goodanime.MediaListEntry
	(MediaListStatus)(0),   // 1: goodanime.MediaListStatus
	(*FuzzyDate)(nil),      // 2: goodanime.FuzzyDate
}
var file_media_list_entry_proto_depIdxs = []int32{
	1, // 0: goodanime.MediaListEntry.status:type_name -> goodanime.MediaListStatus
	2, // 1: goodanime.MediaListEntry.started_at:type_name -> goodanime.FuzzyDate
	2, // 2: goodanime.MediaListEntry.completed_at:type_name -> goodanime.FuzzyDate
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_media_list_entry_proto_init() }
func file_media_list_entry_proto_init() {
	if File_media_list_entry_proto != nil {
		return
	}
	file_common_proto_init()
	file_media_list_entry_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_list_entry_proto_rawDesc), len(file_media_list_entry_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_media_list_entry_proto_goTypes,
		DependencyIndexes: file_media_list_entry_proto_depIdxs,
		MessageInfos:      file_media_list_entry_proto_msgTypes,
	}.Build()
	File_media_list_entry_proto = out.File
	file_media_list_entry_proto_goTypes = nil
	file_media_list_entry_proto_depIdxs = nil
}
