// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: media_min.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Title struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	English       string                 `protobuf:"bytes,1,opt,name=english,proto3" json:"english,omitempty"`
	Native        string                 `protobuf:"bytes,2,opt,name=native,proto3" json:"native,omitempty"`
	Romaji        string                 `protobuf:"bytes,3,opt,name=romaji,proto3" json:"romaji,omitempty"`
	UserPreferred string                 `protobuf:"bytes,4,opt,name=user_preferred,json=userPreferred,proto3" json:"user_preferred,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Title) Reset() {
	*x = Title{}
	mi := &file_media_min_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Title) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Title) ProtoMessage() {}

func (x *Title) ProtoReflect() protoreflect.Message {
	mi := &file_media_min_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Title.ProtoReflect.Descriptor instead.
func (*Title) Descriptor() ([]byte, []int) {
	return file_media_min_proto_rawDescGZIP(), []int{0}
}

func (x *Title) GetEnglish() string {
	if x != nil {
		return x.English
	}
	return ""
}

func (x *Title) GetNative() string {
	if x != nil {
		return x.Native
	}
	return ""
}

func (x *Title) GetRomaji() string {
	if x != nil {
		return x.Romaji
	}
	return ""
}

func (x *Title) GetUserPreferred() string {
	if x != nil {
		return x.UserPreferred
	}
	return ""
}

type CoverImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Medium        string                 `protobuf:"bytes,1,opt,name=medium,proto3" json:"medium,omitempty"`
	Large         string                 `protobuf:"bytes,2,opt,name=large,proto3" json:"large,omitempty"`
	ExtraLarge    string                 `protobuf:"bytes,3,opt,name=extra_large,json=extraLarge,proto3" json:"extra_large,omitempty"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoverImage) Reset() {
	*x = CoverImage{}
	mi := &file_media_min_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoverImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoverImage) ProtoMessage() {}

func (x *CoverImage) ProtoReflect() protoreflect.Message {
	mi := &file_media_min_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoverImage.ProtoReflect.Descriptor instead.
func (*CoverImage) Descriptor() ([]byte, []int) {
	return file_media_min_proto_rawDescGZIP(), []int{1}
}

func (x *CoverImage) GetMedium() string {
	if x != nil {
		return x.Medium
	}
	return ""
}

func (x *CoverImage) GetLarge() string {
	if x != nil {
		return x.Large
	}
	return ""
}

func (x *CoverImage) GetExtraLarge() string {
	if x != nil {
		return x.ExtraLarge
	}
	return ""
}

func (x *CoverImage) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type MediaMin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *Title                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	AverageScore  int32                  `protobuf:"varint,3,opt,name=average_score,json=averageScore,proto3" json:"average_score,omitempty"`
	CoverImage    *CoverImage            `protobuf:"bytes,4,opt,name=cover_image,json=coverImage,proto3" json:"cover_image,omitempty"`
	Episodes      int32                  `protobuf:"varint,5,opt,name=episodes,proto3" json:"episodes,omitempty"`
	Format        string                 `protobuf:"bytes,6,opt,name=format,proto3" json:"format,omitempty"`
	IsAdult       bool                   `protobuf:"varint,7,opt,name=is_adult,json=isAdult,proto3" json:"is_adult,omitempty"`
	IsFavourite   bool                   `protobuf:"varint,8,opt,name=is_favourite,json=isFavourite,proto3" json:"is_favourite,omitempty"`
	SiteUrl       string                 `protobuf:"bytes,9,opt,name=site_url,json=siteUrl,proto3" json:"site_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaMin) Reset() {
	*x = MediaMin{}
	mi := &file_media_min_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaMin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaMin) ProtoMessage() {}

func (x *MediaMin) ProtoReflect() protoreflect.Message {
	mi := &file_media_min_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaMin.ProtoReflect.Descriptor instead.
func (*MediaMin) Descriptor() ([]byte, []int) {
	return file_media_min_proto_rawDescGZIP(), []int{2}
}

func (x *MediaMin) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MediaMin) GetTitle() *Title {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *MediaMin) GetAverageScore() int32 {
	if x != nil {
		return x.AverageScore
	}
	return 0
}

func (x *MediaMin) GetCoverImage() *CoverImage {
	if x != nil {
		return x.CoverImage
	}
	return nil
}

func (x *MediaMin) GetEpisodes() int32 {
	if x != nil {
		return x.Episodes
	}
	return 0
}

func (x *MediaMin) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *MediaMin) GetIsAdult() bool {
	if x != nil {
		return x.IsAdult
	}
	return false
}

func (x *MediaMin) GetIsFavourite() bool {
	if x != nil {
		return x.IsFavourite
	}
	return false
}

func (x *MediaMin) GetSiteUrl() string {
	if x != nil {
		return x.SiteUrl
	}
	return ""
}

var File_media_min_proto protoreflect.FileDescriptor

const file_media_min_proto_rawDesc = "" +
	"\n" +
	"\x0fmedia_min.proto\x12\tgoodanime\"x\n" +
	"\x05Title\x12\x18\n" +
	"\aenglish\x18\x01 \x01(\tR\aenglish\x12\x16\n" +
	"\x06native\x18\x02 \x01(\tR\x06native\x12\x16\n" +
	"\x06romaji\x18\x03 \x01(\tR\x06romaji\x12%\n" +
	"\x0euser_preferred\x18\x04 \x01(\tR\ruserPreferred\"q\n" +
	"\n" +
	"CoverImage\x12\x16\n" +
	"\x06medium\x18\x01 \x01(\tR\x06medium\x12\x14\n" +
	"\x05large\x18\x02 \x01(\tR\x05large\x12\x1f\n" +
	"\vextra_large\x18\x03 \x01(\tR\n" +
	"extraLarge\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\"\xac\x02\n" +
	"\bMediaMin\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12&\n" +
	"\x05title\x18\x02 \x01(\v2\x10.goodanime.TitleR\x05title\x12#\n" +
	"\raverage_score\x18\x03 \x01(\x05R\faverageScore\x126\n" +
	"\vcover_image\x18\x04 \x01(\v2\x15.goodanime.CoverImageR\n" +
	"coverImage\x12\x1a\n" +
	"\bepisodes\x18\x05 \x01(\x05R\bepisodes\x12\x16\n" +
	"\x06format\x18\x06 \x01(\tR\x06format\x12\x19\n" +
	"\bis_adult\x18\a \x01(\bR\aisAdult\x12!\n" +
	"\fis_favourite\x18\b \x01(\bR\visFavourite\x12\x19\n" +
	"\bsite_url\x18\t \x01(\tR\asiteUrlB\x19Z\x17goodanime/backend/protob\x06proto3"

var (
	file_media_min_proto_rawDescOnce sync.Once
	file_media_min_proto_rawDescData []byte
)

func file_media_min_proto_rawDescGZIP() []byte {
	file_media_min_proto_rawDescOnce.Do(func() {
		file_media_min_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_min_proto_rawDesc), len(file_media_min_proto_rawDesc)))
	})
	return file_media_min_proto_rawDescData
}

var file_media_min_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_media_min_proto_goTypes = []any{
	(*Title)(nil),      // 0: goodanime.Title
	(*CoverImage)(nil), // 1: goodanime.CoverImage
	(*MediaMin)(nil),   // 2: goodanime.MediaMin
}
var file_media_min_proto_depIdxs = []int32{
	0, // 0: goodanime.MediaMin.title:type_name -> goodanime.Title
	1, // 1: goodanime.MediaMin.cover_image:type_name -> goodanime.CoverImage
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_media_min_proto_init() }
func file_media_min_proto_init() {
	if File_media_min_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_min_proto_rawDesc), len(file_media_min_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_media_min_proto_goTypes,
		DependencyIndexes: file_media_min_proto_depIdxs,
		MessageInfos:      file_media_min_proto_msgTypes,
	}.Build()
	File_media_min_proto = out.File
	file_media_min_proto_goTypes = nil
	file_media_min_proto_depIdxs = nil
}
