// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: media.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Media struct {
	state             protoimpl.MessageState    `protogen:"open.v1"`
	Base              *MediaMin                 `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Description       string                    `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	BannerImage       string                    `protobuf:"bytes,3,opt,name=banner_image,json=bannerImage,proto3" json:"banner_image,omitempty"`
	Status            string                    `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Genres            []string                  `protobuf:"bytes,5,rep,name=genres,proto3" json:"genres,omitempty"`
	Popularity        int32                     `protobuf:"varint,6,opt,name=popularity,proto3" json:"popularity,omitempty"`
	Season            string                    `protobuf:"bytes,7,opt,name=season,proto3" json:"season,omitempty"`
	SeasonYear        int32                     `protobuf:"varint,8,opt,name=season_year,json=seasonYear,proto3" json:"season_year,omitempty"`
	Type              string                    `protobuf:"bytes,9,opt,name=type,proto3" json:"type,omitempty"`
	Trailer           *Trailer                  `protobuf:"bytes,10,opt,name=trailer,proto3" json:"trailer,omitempty"`
	MediaListEntry    *MediaListEntry           `protobuf:"bytes,11,opt,name=media_list_entry,json=mediaListEntry,proto3" json:"media_list_entry,omitempty"`
	Studios           *StudioConnection         `protobuf:"bytes,12,opt,name=studios,proto3" json:"studios,omitempty"`
	Tags              []*MediaTag               `protobuf:"bytes,13,rep,name=tags,proto3" json:"tags,omitempty"`
	ExternalLinks     []*ExternalLink           `protobuf:"bytes,14,rep,name=external_links,json=externalLinks,proto3" json:"external_links,omitempty"`
	StreamingEpisodes []*StreamingEpisode       `protobuf:"bytes,15,rep,name=streaming_episodes,json=streamingEpisodes,proto3" json:"streaming_episodes,omitempty"`
	Staff             *StaffConnection          `protobuf:"bytes,16,opt,name=staff,proto3" json:"staff,omitempty"`
	NextAiringEpisode *AiringSchedule           `protobuf:"bytes,17,opt,name=next_airing_episode,json=nextAiringEpisode,proto3" json:"next_airing_episode,omitempty"`
	Characters        *CharacterConnection      `protobuf:"bytes,18,opt,name=characters,proto3" json:"characters,omitempty"`
	Relations         *MediaConnection          `protobuf:"bytes,19,opt,name=relations,proto3" json:"relations,omitempty"`
	Recommendations   *RecommendationConnection `protobuf:"bytes,20,opt,name=recommendations,proto3" json:"recommendations,omitempty"`
	Rankings          []*MediaRank              `protobuf:"bytes,21,rep,name=rankings,proto3" json:"rankings,omitempty"`
	Stats             *MediaStats               `protobuf:"bytes,22,opt,name=stats,proto3" json:"stats,omitempty"`
	Trends            *MediaTrendConnection     `protobuf:"bytes,23,opt,name=trends,proto3" json:"trends,omitempty"`
	MeanScore         *int32                    `protobuf:"varint,24,opt,name=mean_score,json=meanScore,proto3,oneof" json:"mean_score,omitempty"`
	Favourites        *int32                    `protobuf:"varint,25,opt,name=favourites,proto3,oneof" json:"favourites,omitempty"`
	Synonyms          []string                  `protobuf:"bytes,26,rep,name=synonyms,proto3" json:"synonyms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{0}
}

func (x *Media) GetBase() *MediaMin {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *Media) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Media) GetBannerImage() string {
	if x != nil {
		return x.BannerImage
	}
	return ""
}

func (x *Media) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Media) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *Media) GetPopularity() int32 {
	if x != nil {
		return x.Popularity
	}
	return 0
}

func (x *Media) GetSeason() string {
	if x != nil {
		return x.Season
	}
	return ""
}

func (x *Media) GetSeasonYear() int32 {
	if x != nil {
		return x.SeasonYear
	}
	return 0
}

func (x *Media) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Media) GetTrailer() *Trailer {
	if x != nil {
		return x.Trailer
	}
	return nil
}

func (x *Media) GetMediaListEntry() *MediaListEntry {
	if x != nil {
		return x.MediaListEntry
	}
	return nil
}

func (x *Media) GetStudios() *StudioConnection {
	if x != nil {
		return x.Studios
	}
	return nil
}

func (x *Media) GetTags() []*MediaTag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Media) GetExternalLinks() []*ExternalLink {
	if x != nil {
		return x.ExternalLinks
	}
	return nil
}

func (x *Media) GetStreamingEpisodes() []*StreamingEpisode {
	if x != nil {
		return x.StreamingEpisodes
	}
	return nil
}

func (x *Media) GetStaff() *StaffConnection {
	if x != nil {
		return x.Staff
	}
	return nil
}

func (x *Media) GetNextAiringEpisode() *AiringSchedule {
	if x != nil {
		return x.NextAiringEpisode
	}
	return nil
}

func (x *Media) GetCharacters() *CharacterConnection {
	if x != nil {
		return x.Characters
	}
	return nil
}

func (x *Media) GetRelations() *MediaConnection {
	if x != nil {
		return x.Relations
	}
	return nil
}

func (x *Media) GetRecommendations() *RecommendationConnection {
	if x != nil {
		return x.Recommendations
	}
	return nil
}

func (x *Media) GetRankings() []*MediaRank {
	if x != nil {
		return x.Rankings
	}
	return nil
}

func (x *Media) GetStats() *MediaStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

func (x *Media) GetTrends() *MediaTrendConnection {
	if x != nil {
		return x.Trends
	}
	return nil
}

func (x *Media) GetMeanScore() int32 {
	if x != nil && x.MeanScore != nil {
		return *x.MeanScore
	}
	return 0
}

func (x *Media) GetFavourites() int32 {
	if x != nil && x.Favourites != nil {
		return *x.Favourites
	}
	return 0
}

func (x *Media) GetSynonyms() []string {
	if x != nil {
		return x.Synonyms
	}
	return nil
}

var File_media_proto protoreflect.FileDescriptor

const file_media_proto_rawDesc = "" +
	"\n" +
	"\vmedia.proto\x12\tgoodanime\x1a\x15media_character.proto\x1a\x10media_edge.proto\x1a\x16media_list_entry.proto\x1a\x0fmedia_min.proto\x1a\x10media_misc.proto\x1a\x1amedia_recommendation.proto\x1a\x11media_staff.proto\x1a\x12media_studio.proto\x1a\x11media_trend.proto\"\xd2\t\n" +
	"\x05Media\x12'\n" +
	"\x04base\x18\x01 \x01(\v2\x13.goodanime.MediaMinR\x04base\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\fbanner_image\x18\x03 \x01(\tR\vbannerImage\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x16\n" +
	"\x06genres\x18\x05 \x03(\tR\x06genres\x12\x1e\n" +
	"\n" +
	"popularity\x18\x06 \x01(\x05R\n" +
	"popularity\x12\x16\n" +
	"\x06season\x18\a \x01(\tR\x06season\x12\x1f\n" +
	"\vseason_year\x18\b \x01(\x05R\n" +
	"seasonYear\x12\x12\n" +
	"\x04type\x18\t \x01(\tR\x04type\x12,\n" +
	"\atrailer\x18\n" +
	" \x01(\v2\x12.goodanime.TrailerR\atrailer\x12C\n" +
	"\x10media_list_entry\x18\v \x01(\v2\x19.goodanime.MediaListEntryR\x0emediaListEntry\x125\n" +
	"\astudios\x18\f \x01(\v2\x1b.goodanime.StudioConnectionR\astudios\x12'\n" +
	"\x04tags\x18\r \x03(\v2\x13.goodanime.MediaTagR\x04tags\x12>\n" +
	"\x0eexternal_links\x18\x0e \x03(\v2\x17.goodanime.ExternalLinkR\rexternalLinks\x12J\n" +
	"\x12streaming_episodes\x18\x0f \x03(\v2\x1b.goodanime.StreamingEpisodeR\x11streamingEpisodes\x120\n" +
	"\x05staff\x18\x10 \x01(\v2\x1a.goodanime.StaffConnectionR\x05staff\x12I\n" +
	"\x13next_airing_episode\x18\x11 \x01(\v2\x19.goodanime.AiringScheduleR\x11nextAiringEpisode\x12>\n" +
	"\n" +
	"characters\x18\x12 \x01(\v2\x1e.goodanime.CharacterConnectionR\n" +
	"characters\x128\n" +
	"\trelations\x18\x13 \x01(\v2\x1a.goodanime.MediaConnectionR\trelations\x12M\n" +
	"\x0frecommendations\x18\x14 \x01(\v2#.goodanime.RecommendationConnectionR\x0frecommendations\x120\n" +
	"\brankings\x18\x15 \x03(\v2\x14.goodanime.MediaRankR\brankings\x12+\n" +
	"\x05stats\x18\x16 \x01(\v2\x15.goodanime.MediaStatsR\x05stats\x127\n" +
	"\x06trends\x18\x17 \x01(\v2\x1f.goodanime.MediaTrendConnectionR\x06trends\x12\"\n" +
	"\n" +
	"mean_score\x18\x18 \x01(\x05H\x00R\tmeanScore\x88\x01\x01\x12#\n" +
	"\n" +
	"favourites\x18\x19 \x01(\x05H\x01R\n" +
	"favourites\x88\x01\x01\x12\x1a\n" +
	"\bsynonyms\x18\x1a \x03(\tR\bsynonymsB\r\n" +
	"\v_mean_scoreB\r\n" +
	"\v_favouritesB\x19Z\x17goodanime/backend/protob\x06proto3"

var (
	file_media_proto_rawDescOnce sync.Once
	file_media_proto_rawDescData []byte
)

func file_media_proto_rawDescGZIP() []byte {
	file_media_proto_rawDescOnce.Do(func() {
		file_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_proto_rawDesc), len(file_media_proto_rawDesc)))
	})
	return file_media_proto_rawDescData
}

var file_media_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_media_proto_goTypes = []any{
	(*Media)(nil),                    // 0: goodanime.Media
	(*MediaMin)(nil),                 // 1: goodanime.MediaMin
	(*Trailer)(nil),                  // 2: goodanime.Trailer
	(*MediaListEntry)(nil),           // 3: goodanime.MediaListEntry
	(*StudioConnection)(nil),         // 4: goodanime.StudioConnection
	(*MediaTag)(nil),                 // 5: goodanime.MediaTag
	(*ExternalLink)(nil),             // 6: goodanime.ExternalLink
	(*StreamingEpisode)(nil),         // 7: goodanime.StreamingEpisode
	(*StaffConnection)(nil),          // 8: goodanime.StaffConnection
	(*AiringSchedule)(nil),           // 9: goodanime.AiringSchedule
	(*CharacterConnection)(nil),      // 10: goodanime.CharacterConnection
	(*MediaConnection)(nil),          // 11: goodanime.MediaConnection
	(*RecommendationConnection)(nil), // 12: goodanime.RecommendationConnection
	(*MediaRank)(nil),                // 13: goodanime.MediaRank
	(*MediaStats)(nil),               // 14: goodanime.MediaStats
	(*MediaTrendConnection)(nil),     // 15: goodanime.MediaTrendConnection
}
var file_media_proto_depIdxs = []int32{
	1,  // 0: goodanime.Media.base:type_name -> goodanime.MediaMin
	2,  // 1: goodanime.Media.trailer:type_name -> goodanime.Trailer
	3,  // 2: goodanime.Media.media_list_entry:type_name -> goodanime.MediaListEntry
	4,  // 3: goodanime.Media.studios:type_name -> goodanime.StudioConnection
	5,  // 4: goodanime.Media.tags:type_name -> goodanime.MediaTag
	6,  // 5: goodanime.Media.external_links:type_name -> goodanime.ExternalLink
	7,  // 6: goodanime.Media.streaming_episodes:type_name -> goodanime.StreamingEpisode
	8,  // 7: goodanime.Media.staff:type_name -> goodanime.StaffConnection
	9,  // 8: goodanime.Media.next_airing_episode:type_name -> goodanime.AiringSchedule
	10, // 9: goodanime.Media.characters:type_name -> goodanime.CharacterConnection
	11, // 10: goodanime.Media.relations:type_name -> goodanime.MediaConnection
	12, // 11: goodanime.Media.recommendations:type_name -> goodanime.RecommendationConnection
	13, // 12: goodanime.Media.rankings:type_name -> goodanime.MediaRank
	14, // 13: goodanime.Media.stats:type_name -> goodanime.MediaStats
	15, // 14: goodanime.Media.trends:type_name -> goodanime.MediaTrendConnection
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_media_proto_init() }
func file_media_proto_init() {
	if File_media_proto != nil {
		return
	}
	file_media_character_proto_init()
	file_media_edge_proto_init()
	file_media_list_entry_proto_init()
	file_media_min_proto_init()
	file_media_misc_proto_init()
	file_media_recommendation_proto_init()
	file_media_staff_proto_init()
	file_media_studio_proto_init()
	file_media_trend_proto_init()
	file_media_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_proto_rawDesc), len(file_media_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_media_proto_goTypes,
		DependencyIndexes: file_media_proto_depIdxs,
		MessageInfos:      file_media_proto_msgTypes,
	}.Build()
	File_media_proto = out.File
	file_media_proto_goTypes = nil
	file_media_proto_depIdxs = nil
}
