// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: media_recommendation.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Recommendation struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Rating              int32                  `protobuf:"varint,1,opt,name=rating,proto3" json:"rating,omitempty"`
	MediaRecommendation *MediaMin              `protobuf:"bytes,2,opt,name=media_recommendation,json=mediaRecommendation,proto3" json:"media_recommendation,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Recommendation) Reset() {
	*x = Recommendation{}
	mi := &file_media_recommendation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recommendation) ProtoMessage() {}

func (x *Recommendation) ProtoReflect() protoreflect.Message {
	mi := &file_media_recommendation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recommendation.ProtoReflect.Descriptor instead.
func (*Recommendation) Descriptor() ([]byte, []int) {
	return file_media_recommendation_proto_rawDescGZIP(), []int{0}
}

func (x *Recommendation) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *Recommendation) GetMediaRecommendation() *MediaMin {
	if x != nil {
		return x.MediaRecommendation
	}
	return nil
}

type RecommendationEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Recommendation        `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendationEdge) Reset() {
	*x = RecommendationEdge{}
	mi := &file_media_recommendation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationEdge) ProtoMessage() {}

func (x *RecommendationEdge) ProtoReflect() protoreflect.Message {
	mi := &file_media_recommendation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationEdge.ProtoReflect.Descriptor instead.
func (*RecommendationEdge) Descriptor() ([]byte, []int) {
	return file_media_recommendation_proto_rawDescGZIP(), []int{1}
}

func (x *RecommendationEdge) GetNode() *Recommendation {
	if x != nil {
		return x.Node
	}
	return nil
}

type RecommendationConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageInfo      *PageInfo              `protobuf:"bytes,1,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	Edges         []*RecommendationEdge  `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecommendationConnection) Reset() {
	*x = RecommendationConnection{}
	mi := &file_media_recommendation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecommendationConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendationConnection) ProtoMessage() {}

func (x *RecommendationConnection) ProtoReflect() protoreflect.Message {
	mi := &file_media_recommendation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendationConnection.ProtoReflect.Descriptor instead.
func (*RecommendationConnection) Descriptor() ([]byte, []int) {
	return file_media_recommendation_proto_rawDescGZIP(), []int{2}
}

func (x *RecommendationConnection) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *RecommendationConnection) GetEdges() []*RecommendationEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

var File_media_recommendation_proto protoreflect.FileDescriptor

const file_media_recommendation_proto_rawDesc = "" +
	"\n" +
	"\x1amedia_recommendation.proto\x12\tgoodanime\x1a\fcommon.proto\x1a\x0fmedia_min.proto\"p\n" +
	"\x0eRecommendation\x12\x16\n" +
	"\x06rating\x18\x01 \x01(\x05R\x06rating\x12F\n" +
	"\x14media_recommendation\x18\x02 \x01(\v2\x13.goodanime.MediaMinR\x13mediaRecommendation\"C\n" +
	"\x12RecommendationEdge\x12-\n" +
	"\x04node\x18\x01 \x01(\v2\x19.goodanime.RecommendationR\x04node\"\x81\x01\n" +
	"\x18RecommendationConnection\x120\n" +
	"\tpage_info\x18\x01 \x01(\v2\x13.goodanime.PageInfoR\bpageInfo\x123\n" +
	"\x05edges\x18\x02 \x03(\v2\x1d.goodanime.RecommendationEdgeR\x05edgesB\x19Z\x17goodanime/backend/protob\x06proto3"

var (
	file_media_recommendation_proto_rawDescOnce sync.Once
	file_media_recommendation_proto_rawDescData []byte
)

func file_media_recommendation_proto_rawDescGZIP() []byte {
	file_media_recommendation_proto_rawDescOnce.Do(func() {
		file_media_recommendation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_recommendation_proto_rawDesc), len(file_media_recommendation_proto_rawDesc)))
	})
	return file_media_recommendation_proto_rawDescData
}

var file_media_recommendation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_media_recommendation_proto_goTypes = []any{
	(*Recommendation)(nil),           // 0: goodanime.Recommendation
	(*RecommendationEdge)(nil),       // 1: goodanime.RecommendationEdge
	(*RecommendationConnection)(nil), // 2: goodanime.RecommendationConnection
	(*MediaMin)(nil),                 // 3: goodanime.MediaMin
	(*PageInfo)(nil),                 // 4: goodanime.PageInfo
}
var file_media_recommendation_proto_depIdxs = []int32{
	3, // 0: goodanime.Recommendation.media_recommendation:type_name -> goodanime.MediaMin
	0, // 1: goodanime.RecommendationEdge.node:type_name -> goodanime.Recommendation
	4, // 2: goodanime.RecommendationConnection.page_info:type_name -> goodanime.PageInfo
	1, // 3: goodanime.RecommendationConnection.edges:type_name -> goodanime.RecommendationEdge
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_media_recommendation_proto_init() }
func file_media_recommendation_proto_init() {
	if File_media_recommendation_proto != nil {
		return
	}
	file_common_proto_init()
	file_media_min_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_recommendation_proto_rawDesc), len(file_media_recommendation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_media_recommendation_proto_goTypes,
		DependencyIndexes: file_media_recommendation_proto_depIdxs,
		MessageInfos:      file_media_recommendation_proto_msgTypes,
	}.Build()
	File_media_recommendation_proto = out.File
	file_media_recommendation_proto_goTypes = nil
	file_media_recommendation_proto_depIdxs = nil
}
