// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: media_staff.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StaffName struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Full          string                 `protobuf:"bytes,1,opt,name=full,proto3" json:"full,omitempty"`
	Native        *string                `protobuf:"bytes,2,opt,name=native,proto3,oneof" json:"native,omitempty"`
	UserPreferred *string                `protobuf:"bytes,3,opt,name=user_preferred,json=userPreferred,proto3,oneof" json:"user_preferred,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaffName) Reset() {
	*x = StaffName{}
	mi := &file_media_staff_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaffName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffName) ProtoMessage() {}

func (x *StaffName) ProtoReflect() protoreflect.Message {
	mi := &file_media_staff_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffName.ProtoReflect.Descriptor instead.
func (*StaffName) Descriptor() ([]byte, []int) {
	return file_media_staff_proto_rawDescGZIP(), []int{0}
}

func (x *StaffName) GetFull() string {
	if x != nil {
		return x.Full
	}
	return ""
}

func (x *StaffName) GetNative() string {
	if x != nil && x.Native != nil {
		return *x.Native
	}
	return ""
}

func (x *StaffName) GetUserPreferred() string {
	if x != nil && x.UserPreferred != nil {
		return *x.UserPreferred
	}
	return ""
}

type StaffImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Large         *string                `protobuf:"bytes,1,opt,name=large,proto3,oneof" json:"large,omitempty"`
	Medium        *string                `protobuf:"bytes,2,opt,name=medium,proto3,oneof" json:"medium,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaffImage) Reset() {
	*x = StaffImage{}
	mi := &file_media_staff_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaffImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffImage) ProtoMessage() {}

func (x *StaffImage) ProtoReflect() protoreflect.Message {
	mi := &file_media_staff_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffImage.ProtoReflect.Descriptor instead.
func (*StaffImage) Descriptor() ([]byte, []int) {
	return file_media_staff_proto_rawDescGZIP(), []int{1}
}

func (x *StaffImage) GetLarge() string {
	if x != nil && x.Large != nil {
		return *x.Large
	}
	return ""
}

func (x *StaffImage) GetMedium() string {
	if x != nil && x.Medium != nil {
		return *x.Medium
	}
	return ""
}

type Staff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *StaffName             `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image         *StaffImage            `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	LanguageV2    *string                `protobuf:"bytes,3,opt,name=language_v2,json=languageV2,proto3,oneof" json:"language_v2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Staff) Reset() {
	*x = Staff{}
	mi := &file_media_staff_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Staff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Staff) ProtoMessage() {}

func (x *Staff) ProtoReflect() protoreflect.Message {
	mi := &file_media_staff_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Staff.ProtoReflect.Descriptor instead.
func (*Staff) Descriptor() ([]byte, []int) {
	return file_media_staff_proto_rawDescGZIP(), []int{2}
}

func (x *Staff) GetName() *StaffName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Staff) GetImage() *StaffImage {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *Staff) GetLanguageV2() string {
	if x != nil && x.LanguageV2 != nil {
		return *x.LanguageV2
	}
	return ""
}

type StaffEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Node          *Staff                 `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaffEdge) Reset() {
	*x = StaffEdge{}
	mi := &file_media_staff_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaffEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffEdge) ProtoMessage() {}

func (x *StaffEdge) ProtoReflect() protoreflect.Message {
	mi := &file_media_staff_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffEdge.ProtoReflect.Descriptor instead.
func (*StaffEdge) Descriptor() ([]byte, []int) {
	return file_media_staff_proto_rawDescGZIP(), []int{3}
}

func (x *StaffEdge) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *StaffEdge) GetNode() *Staff {
	if x != nil {
		return x.Node
	}
	return nil
}

type StaffConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edges         []*StaffEdge           `protobuf:"bytes,1,rep,name=edges,proto3" json:"edges,omitempty"`
	PageInfo      *PageInfo              `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StaffConnection) Reset() {
	*x = StaffConnection{}
	mi := &file_media_staff_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StaffConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StaffConnection) ProtoMessage() {}

func (x *StaffConnection) ProtoReflect() protoreflect.Message {
	mi := &file_media_staff_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StaffConnection.ProtoReflect.Descriptor instead.
func (*StaffConnection) Descriptor() ([]byte, []int) {
	return file_media_staff_proto_rawDescGZIP(), []int{4}
}

func (x *StaffConnection) GetEdges() []*StaffEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *StaffConnection) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

var File_media_staff_proto protoreflect.FileDescriptor

const file_media_staff_proto_rawDesc = "" +
	"\n" +
	"\x11media_staff.proto\x12\tgoodanime\x1a\fcommon.proto\"\x86\x01\n" +
	"\tStaffName\x12\x12\n" +
	"\x04full\x18\x01 \x01(\tR\x04full\x12\x1b\n" +
	"\x06native\x18\x02 \x01(\tH\x00R\x06native\x88\x01\x01\x12*\n" +
	"\x0euser_preferred\x18\x03 \x01(\tH\x01R\ruserPreferred\x88\x01\x01B\t\n" +
	"\a_nativeB\x11\n" +
	"\x0f_user_preferred\"Y\n" +
	"\n" +
	"StaffImage\x12\x19\n" +
	"\x05large\x18\x01 \x01(\tH\x00R\x05large\x88\x01\x01\x12\x1b\n" +
	"\x06medium\x18\x02 \x01(\tH\x01R\x06medium\x88\x01\x01B\b\n" +
	"\x06_largeB\t\n" +
	"\a_medium\"\x94\x01\n" +
	"\x05Staff\x12(\n" +
	"\x04name\x18\x01 \x01(\v2\x14.goodanime.StaffNameR\x04name\x12+\n" +
	"\x05image\x18\x02 \x01(\v2\x15.goodanime.StaffImageR\x05image\x12$\n" +
	"\vlanguage_v2\x18\x03 \x01(\tH\x00R\n" +
	"languageV2\x88\x01\x01B\x0e\n" +
	"\f_language_v2\"E\n" +
	"\tStaffEdge\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12$\n" +
	"\x04node\x18\x02 \x01(\v2\x10.goodanime.StaffR\x04node\"o\n" +
	"\x0fStaffConnection\x12*\n" +
	"\x05edges\x18\x01 \x03(\v2\x14.goodanime.StaffEdgeR\x05edges\x120\n" +
	"\tpage_info\x18\x02 \x01(\v2\x13.goodanime.PageInfoR\bpageInfoB\x19Z\x17goodanime/backend/protob\x06proto3"

var (
	file_media_staff_proto_rawDescOnce sync.Once
	file_media_staff_proto_rawDescData []byte
)

func file_media_staff_proto_rawDescGZIP() []byte {
	file_media_staff_proto_rawDescOnce.Do(func() {
		file_media_staff_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_staff_proto_rawDesc), len(file_media_staff_proto_rawDesc)))
	})
	return file_media_staff_proto_rawDescData
}

var file_media_staff_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_media_staff_proto_goTypes = []any{
	(*StaffName)(nil),       // 0: goodanime.StaffName
	(*StaffImage)(nil),      // 1: goodanime.StaffImage
	(*Staff)(nil),           // 2: goodanime.Staff
	(*StaffEdge)(nil),       // 3: goodanime.StaffEdge
	(*StaffConnection)(nil), // 4: goodanime.StaffConnection
	(*PageInfo)(nil),        // 5: goodanime.PageInfo
}
var file_media_staff_proto_depIdxs = []int32{
	0, // 0: goodanime.Staff.name:type_name -> goodanime.StaffName
	1, // 1: goodanime.Staff.image:type_name -> goodanime.StaffImage
	2, // 2: goodanime.StaffEdge.node:type_name -> goodanime.Staff
	3, // 3: goodanime.StaffConnection.edges:type_name -> goodanime.StaffEdge
	5, // 4: goodanime.StaffConnection.page_info:type_name -> goodanime.PageInfo
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_media_staff_proto_init() }
func file_media_staff_proto_init() {
	if File_media_staff_proto != nil {
		return
	}
	file_common_proto_init()
	file_media_staff_proto_msgTypes[0].OneofWrappers = []any{}
	file_media_staff_proto_msgTypes[1].OneofWrappers = []any{}
	file_media_staff_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_staff_proto_rawDesc), len(file_media_staff_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_media_staff_proto_goTypes,
		DependencyIndexes: file_media_staff_proto_depIdxs,
		MessageInfos:      file_media_staff_proto_msgTypes,
	}.Build()
	File_media_staff_proto = out.File
	file_media_staff_proto_goTypes = nil
	file_media_staff_proto_depIdxs = nil
}
