// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: media_trend.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaTrend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AverageScore  int32                  `protobuf:"varint,1,opt,name=average_score,json=averageScore,proto3" json:"average_score,omitempty"`
	Date          int32                  `protobuf:"varint,2,opt,name=date,proto3" json:"date,omitempty"`
	InProgress    int32                  `protobuf:"varint,3,opt,name=in_progress,json=inProgress,proto3" json:"in_progress,omitempty"`
	Popularity    int32                  `protobuf:"varint,4,opt,name=popularity,proto3" json:"popularity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaTrend) Reset() {
	*x = MediaTrend{}
	mi := &file_media_trend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaTrend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaTrend) ProtoMessage() {}

func (x *MediaTrend) ProtoReflect() protoreflect.Message {
	mi := &file_media_trend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaTrend.ProtoReflect.Descriptor instead.
func (*MediaTrend) Descriptor() ([]byte, []int) {
	return file_media_trend_proto_rawDescGZIP(), []int{0}
}

func (x *MediaTrend) GetAverageScore() int32 {
	if x != nil {
		return x.AverageScore
	}
	return 0
}

func (x *MediaTrend) GetDate() int32 {
	if x != nil {
		return x.Date
	}
	return 0
}

func (x *MediaTrend) GetInProgress() int32 {
	if x != nil {
		return x.InProgress
	}
	return 0
}

func (x *MediaTrend) GetPopularity() int32 {
	if x != nil {
		return x.Popularity
	}
	return 0
}

type MediaTrendConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*MediaTrend          `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaTrendConnection) Reset() {
	*x = MediaTrendConnection{}
	mi := &file_media_trend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaTrendConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaTrendConnection) ProtoMessage() {}

func (x *MediaTrendConnection) ProtoReflect() protoreflect.Message {
	mi := &file_media_trend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaTrendConnection.ProtoReflect.Descriptor instead.
func (*MediaTrendConnection) Descriptor() ([]byte, []int) {
	return file_media_trend_proto_rawDescGZIP(), []int{1}
}

func (x *MediaTrendConnection) GetNodes() []*MediaTrend {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_media_trend_proto protoreflect.FileDescriptor

const file_media_trend_proto_rawDesc = "" +
	"\n" +
	"\x11media_trend.proto\x12\tgoodanime\"\x86\x01\n" +
	"\n" +
	"MediaTrend\x12#\n" +
	"\raverage_score\x18\x01 \x01(\x05R\faverageScore\x12\x12\n" +
	"\x04date\x18\x02 \x01(\x05R\x04date\x12\x1f\n" +
	"\vin_progress\x18\x03 \x01(\x05R\n" +
	"inProgress\x12\x1e\n" +
	"\n" +
	"popularity\x18\x04 \x01(\x05R\n" +
	"popularity\"C\n" +
	"\x14MediaTrendConnection\x12+\n" +
	"\x05nodes\x18\x01 \x03(\v2\x15.goodanime.MediaTrendR\x05nodesB\x19Z\x17goodanime/backend/protob\x06proto3"

var (
	file_media_trend_proto_rawDescOnce sync.Once
	file_media_trend_proto_rawDescData []byte
)

func file_media_trend_proto_rawDescGZIP() []byte {
	file_media_trend_proto_rawDescOnce.Do(func() {
		file_media_trend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_trend_proto_rawDesc), len(file_media_trend_proto_rawDesc)))
	})
	return file_media_trend_proto_rawDescData
}

var file_media_trend_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_media_trend_proto_goTypes = []any{
	(*MediaTrend)(nil),           // 0: goodanime.MediaTrend
	(*MediaTrendConnection)(nil), // 1: goodanime.MediaTrendConnection
}
var file_media_trend_proto_depIdxs = []int32{
	0, // 0: goodanime.MediaTrendConnection.nodes:type_name -> goodanime.MediaTrend
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_media_trend_proto_init() }
func file_media_trend_proto_init() {
	if File_media_trend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_trend_proto_rawDesc), len(file_media_trend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_media_trend_proto_goTypes,
		DependencyIndexes: file_media_trend_proto_depIdxs,
		MessageInfos:      file_media_trend_proto_msgTypes,
	}.Build()
	File_media_trend_proto = out.File
	file_media_trend_proto_goTypes = nil
	file_media_trend_proto_depIdxs = nil
}
