// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: media_edge.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RelationType  string                 `protobuf:"bytes,1,opt,name=relation_type,json=relationType,proto3" json:"relation_type,omitempty"`
	Node          *MediaMin              `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaEdge) Reset() {
	*x = MediaEdge{}
	mi := &file_media_edge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaEdge) ProtoMessage() {}

func (x *MediaEdge) ProtoReflect() protoreflect.Message {
	mi := &file_media_edge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaEdge.ProtoReflect.Descriptor instead.
func (*MediaEdge) Descriptor() ([]byte, []int) {
	return file_media_edge_proto_rawDescGZIP(), []int{0}
}

func (x *MediaEdge) GetRelationType() string {
	if x != nil {
		return x.RelationType
	}
	return ""
}

func (x *MediaEdge) GetNode() *MediaMin {
	if x != nil {
		return x.Node
	}
	return nil
}

type MediaConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edges         []*MediaEdge           `protobuf:"bytes,1,rep,name=edges,proto3" json:"edges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaConnection) Reset() {
	*x = MediaConnection{}
	mi := &file_media_edge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaConnection) ProtoMessage() {}

func (x *MediaConnection) ProtoReflect() protoreflect.Message {
	mi := &file_media_edge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaConnection.ProtoReflect.Descriptor instead.
func (*MediaConnection) Descriptor() ([]byte, []int) {
	return file_media_edge_proto_rawDescGZIP(), []int{1}
}

func (x *MediaConnection) GetEdges() []*MediaEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

var File_media_edge_proto protoreflect.FileDescriptor

const file_media_edge_proto_rawDesc = "" +
	"\n" +
	"\x10media_edge.proto\x12\tgoodanime\x1a\x0fmedia_min.proto\"Y\n" +
	"\tMediaEdge\x12#\n" +
	"\rrelation_type\x18\x01 \x01(\tR\frelationType\x12'\n" +
	"\x04node\x18\x02 \x01(\v2\x13.goodanime.MediaMinR\x04node\"=\n" +
	"\x0fMediaConnection\x12*\n" +
	"\x05edges\x18\x01 \x03(\v2\x14.goodanime.MediaEdgeR\x05edgesB\x19Z\x17goodanime/backend/protob\x06proto3"

var (
	file_media_edge_proto_rawDescOnce sync.Once
	file_media_edge_proto_rawDescData []byte
)

func file_media_edge_proto_rawDescGZIP() []byte {
	file_media_edge_proto_rawDescOnce.Do(func() {
		file_media_edge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_edge_proto_rawDesc), len(file_media_edge_proto_rawDesc)))
	})
	return file_media_edge_proto_rawDescData
}

var file_media_edge_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_media_edge_proto_goTypes = []any{
	(*MediaEdge)(nil),       // 0: goodanime.MediaEdge
	(*MediaConnection)(nil), // 1: goodanime.MediaConnection
	(*MediaMin)(nil),        // 2: goodanime.MediaMin
}
var file_media_edge_proto_depIdxs = []int32{
	2, // 0: goodanime.MediaEdge.node:type_name -> goodanime.MediaMin
	0, // 1: goodanime.MediaConnection.edges:type_name -> goodanime.MediaEdge
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_media_edge_proto_init() }
func file_media_edge_proto_init() {
	if File_media_edge_proto != nil {
		return
	}
	file_media_min_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_edge_proto_rawDesc), len(file_media_edge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_media_edge_proto_goTypes,
		DependencyIndexes: file_media_edge_proto_depIdxs,
		MessageInfos:      file_media_edge_proto_msgTypes,
	}.Build()
	File_media_edge_proto = out.File
	file_media_edge_proto_goTypes = nil
	file_media_edge_proto_depIdxs = nil
}
