// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: media_misc.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Trailer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Site          string                 `protobuf:"bytes,2,opt,name=site,proto3" json:"site,omitempty"`
	Thumbnail     string                 `protobuf:"bytes,3,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trailer) Reset() {
	*x = Trailer{}
	mi := &file_media_misc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trailer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trailer) ProtoMessage() {}

func (x *Trailer) ProtoReflect() protoreflect.Message {
	mi := &file_media_misc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trailer.ProtoReflect.Descriptor instead.
func (*Trailer) Descriptor() ([]byte, []int) {
	return file_media_misc_proto_rawDescGZIP(), []int{0}
}

func (x *Trailer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Trailer) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *Trailer) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

type MediaTag struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IsGeneralSpoiler bool                   `protobuf:"varint,2,opt,name=is_general_spoiler,json=isGeneralSpoiler,proto3" json:"is_general_spoiler,omitempty"`
	IsMediaSpoiler   bool                   `protobuf:"varint,3,opt,name=is_media_spoiler,json=isMediaSpoiler,proto3" json:"is_media_spoiler,omitempty"`
	Name             string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Rank             int32                  `protobuf:"varint,5,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MediaTag) Reset() {
	*x = MediaTag{}
	mi := &file_media_misc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaTag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaTag) ProtoMessage() {}

func (x *MediaTag) ProtoReflect() protoreflect.Message {
	mi := &file_media_misc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaTag.ProtoReflect.Descriptor instead.
func (*MediaTag) Descriptor() ([]byte, []int) {
	return file_media_misc_proto_rawDescGZIP(), []int{1}
}

func (x *MediaTag) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MediaTag) GetIsGeneralSpoiler() bool {
	if x != nil {
		return x.IsGeneralSpoiler
	}
	return false
}

func (x *MediaTag) GetIsMediaSpoiler() bool {
	if x != nil {
		return x.IsMediaSpoiler
	}
	return false
}

func (x *MediaTag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MediaTag) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type ExternalLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Site          string                 `protobuf:"bytes,2,opt,name=site,proto3" json:"site,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalLink) Reset() {
	*x = ExternalLink{}
	mi := &file_media_misc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalLink) ProtoMessage() {}

func (x *ExternalLink) ProtoReflect() protoreflect.Message {
	mi := &file_media_misc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalLink.ProtoReflect.Descriptor instead.
func (*ExternalLink) Descriptor() ([]byte, []int) {
	return file_media_misc_proto_rawDescGZIP(), []int{2}
}

func (x *ExternalLink) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ExternalLink) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *ExternalLink) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type AiringSchedule struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AiringAt        int32                  `protobuf:"varint,1,opt,name=airing_at,json=airingAt,proto3" json:"airing_at,omitempty"`
	Episode         int32                  `protobuf:"varint,2,opt,name=episode,proto3" json:"episode,omitempty"`
	TimeUntilAiring int32                  `protobuf:"varint,3,opt,name=time_until_airing,json=timeUntilAiring,proto3" json:"time_until_airing,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AiringSchedule) Reset() {
	*x = AiringSchedule{}
	mi := &file_media_misc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AiringSchedule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiringSchedule) ProtoMessage() {}

func (x *AiringSchedule) ProtoReflect() protoreflect.Message {
	mi := &file_media_misc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiringSchedule.ProtoReflect.Descriptor instead.
func (*AiringSchedule) Descriptor() ([]byte, []int) {
	return file_media_misc_proto_rawDescGZIP(), []int{3}
}

func (x *AiringSchedule) GetAiringAt() int32 {
	if x != nil {
		return x.AiringAt
	}
	return 0
}

func (x *AiringSchedule) GetEpisode() int32 {
	if x != nil {
		return x.Episode
	}
	return 0
}

func (x *AiringSchedule) GetTimeUntilAiring() int32 {
	if x != nil {
		return x.TimeUntilAiring
	}
	return 0
}

type StreamingEpisode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Thumbnail     string                 `protobuf:"bytes,1,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamingEpisode) Reset() {
	*x = StreamingEpisode{}
	mi := &file_media_misc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamingEpisode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamingEpisode) ProtoMessage() {}

func (x *StreamingEpisode) ProtoReflect() protoreflect.Message {
	mi := &file_media_misc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamingEpisode.ProtoReflect.Descriptor instead.
func (*StreamingEpisode) Descriptor() ([]byte, []int) {
	return file_media_misc_proto_rawDescGZIP(), []int{4}
}

func (x *StreamingEpisode) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

func (x *StreamingEpisode) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *StreamingEpisode) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type MediaRank struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AllTime       bool                   `protobuf:"varint,1,opt,name=all_time,json=allTime,proto3" json:"all_time,omitempty"`
	Rank          int32                  `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Season        string                 `protobuf:"bytes,4,opt,name=season,proto3" json:"season,omitempty"`
	Year          int32                  `protobuf:"varint,5,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaRank) Reset() {
	*x = MediaRank{}
	mi := &file_media_misc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaRank) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaRank) ProtoMessage() {}

func (x *MediaRank) ProtoReflect() protoreflect.Message {
	mi := &file_media_misc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaRank.ProtoReflect.Descriptor instead.
func (*MediaRank) Descriptor() ([]byte, []int) {
	return file_media_misc_proto_rawDescGZIP(), []int{5}
}

func (x *MediaRank) GetAllTime() bool {
	if x != nil {
		return x.AllTime
	}
	return false
}

func (x *MediaRank) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *MediaRank) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MediaRank) GetSeason() string {
	if x != nil {
		return x.Season
	}
	return ""
}

func (x *MediaRank) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type ScoreDistribution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int32                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScoreDistribution) Reset() {
	*x = ScoreDistribution{}
	mi := &file_media_misc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreDistribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreDistribution) ProtoMessage() {}

func (x *ScoreDistribution) ProtoReflect() protoreflect.Message {
	mi := &file_media_misc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreDistribution.ProtoReflect.Descriptor instead.
func (*ScoreDistribution) Descriptor() ([]byte, []int) {
	return file_media_misc_proto_rawDescGZIP(), []int{6}
}

func (x *ScoreDistribution) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ScoreDistribution) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type StatusDistribution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int32                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusDistribution) Reset() {
	*x = StatusDistribution{}
	mi := &file_media_misc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusDistribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusDistribution) ProtoMessage() {}

func (x *StatusDistribution) ProtoReflect() protoreflect.Message {
	mi := &file_media_misc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusDistribution.ProtoReflect.Descriptor instead.
func (*StatusDistribution) Descriptor() ([]byte, []int) {
	return file_media_misc_proto_rawDescGZIP(), []int{7}
}

func (x *StatusDistribution) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *StatusDistribution) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type MediaStats struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ScoreDistribution  []*ScoreDistribution   `protobuf:"bytes,1,rep,name=score_distribution,json=scoreDistribution,proto3" json:"score_distribution,omitempty"`
	StatusDistribution []*StatusDistribution  `protobuf:"bytes,2,rep,name=status_distribution,json=statusDistribution,proto3" json:"status_distribution,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MediaStats) Reset() {
	*x = MediaStats{}
	mi := &file_media_misc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaStats) ProtoMessage() {}

func (x *MediaStats) ProtoReflect() protoreflect.Message {
	mi := &file_media_misc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaStats.ProtoReflect.Descriptor instead.
func (*MediaStats) Descriptor() ([]byte, []int) {
	return file_media_misc_proto_rawDescGZIP(), []int{8}
}

func (x *MediaStats) GetScoreDistribution() []*ScoreDistribution {
	if x != nil {
		return x.ScoreDistribution
	}
	return nil
}

func (x *MediaStats) GetStatusDistribution() []*StatusDistribution {
	if x != nil {
		return x.StatusDistribution
	}
	return nil
}

var File_media_misc_proto protoreflect.FileDescriptor

const file_media_misc_proto_rawDesc = "" +
	"\n" +
	"\x10media_misc.proto\x12\tgoodanime\"K\n" +
	"\aTrailer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04site\x18\x02 \x01(\tR\x04site\x12\x1c\n" +
	"\tthumbnail\x18\x03 \x01(\tR\tthumbnail\"\x9a\x01\n" +
	"\bMediaTag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12,\n" +
	"\x12is_general_spoiler\x18\x02 \x01(\bR\x10isGeneralSpoiler\x12(\n" +
	"\x10is_media_spoiler\x18\x03 \x01(\bR\x0eisMediaSpoiler\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x12\n" +
	"\x04rank\x18\x05 \x01(\x05R\x04rank\"P\n" +
	"\fExternalLink\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12\x12\n" +
	"\x04site\x18\x02 \x01(\tR\x04site\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"s\n" +
	"\x0eAiringSchedule\x12\x1b\n" +
	"\tairing_at\x18\x01 \x01(\x05R\bairingAt\x12\x18\n" +
	"\aepisode\x18\x02 \x01(\x05R\aepisode\x12*\n" +
	"\x11time_until_airing\x18\x03 \x01(\x05R\x0ftimeUntilAiring\"X\n" +
	"\x10StreamingEpisode\x12\x1c\n" +
	"\tthumbnail\x18\x01 \x01(\tR\tthumbnail\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\"z\n" +
	"\tMediaRank\x12\x19\n" +
	"\ball_time\x18\x01 \x01(\bR\aallTime\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\x05R\x04rank\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x16\n" +
	"\x06season\x18\x04 \x01(\tR\x06season\x12\x12\n" +
	"\x04year\x18\x05 \x01(\x05R\x04year\"A\n" +
	"\x11ScoreDistribution\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x05R\x06amount\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\"D\n" +
	"\x12StatusDistribution\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x05R\x06amount\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"\xa9\x01\n" +
	"\n" +
	"MediaStats\x12K\n" +
	"\x12score_distribution\x18\x01 \x03(\v2\x1c.goodanime.ScoreDistributionR\x11scoreDistribution\x12N\n" +
	"\x13status_distribution\x18\x02 \x03(\v2\x1d.goodanime.StatusDistributionR\x12statusDistributionB\x19Z\x17goodanime/backend/protob\x06proto3"

var (
	file_media_misc_proto_rawDescOnce sync.Once
	file_media_misc_proto_rawDescData []byte
)

func file_media_misc_proto_rawDescGZIP() []byte {
	file_media_misc_proto_rawDescOnce.Do(func() {
		file_media_misc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_misc_proto_rawDesc), len(file_media_misc_proto_rawDesc)))
	})
	return file_media_misc_proto_rawDescData
}

var file_media_misc_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_media_misc_proto_goTypes = []any{
	(*Trailer)(nil),            // 0: goodanime.Trailer
	(*MediaTag)(nil),           // 1: goodanime.MediaTag
	(*ExternalLink)(nil),       // 2: goodanime.ExternalLink
	(*AiringSchedule)(nil),     // 3: goodanime.AiringSchedule
	(*StreamingEpisode)(nil),   // 4: goodanime.StreamingEpisode
	(*MediaRank)(nil),          // 5: goodanime.MediaRank
	(*ScoreDistribution)(nil),  // 6: goodanime.ScoreDistribution
	(*StatusDistribution)(nil), // 7: goodanime.StatusDistribution
	(*MediaStats)(nil),         // 8: goodanime.MediaStats
}
var file_media_misc_proto_depIdxs = []int32{
	6, // 0: goodanime.MediaStats.score_distribution:type_name -> goodanime.ScoreDistribution
	7, // 1: goodanime.MediaStats.status_distribution:type_name -> goodanime.StatusDistribution
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_media_misc_proto_init() }
func file_media_misc_proto_init() {
	if File_media_misc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_misc_proto_rawDesc), len(file_media_misc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_media_misc_proto_goTypes,
		DependencyIndexes: file_media_misc_proto_depIdxs,
		MessageInfos:      file_media_misc_proto_msgTypes,
	}.Build()
	File_media_misc_proto = out.File
	file_media_misc_proto_goTypes = nil
	file_media_misc_proto_depIdxs = nil
}
