// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: media_activity.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListActivity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     int32                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IsLiked       bool                   `protobuf:"varint,3,opt,name=is_liked,json=isLiked,proto3" json:"is_liked,omitempty"`
	LikeCount     int32                  `protobuf:"varint,4,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	Progress      string                 `protobuf:"bytes,5,opt,name=progress,proto3" json:"progress,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	User          *Viewer                `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListActivity) Reset() {
	*x = ListActivity{}
	mi := &file_media_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListActivity) ProtoMessage() {}

func (x *ListActivity) ProtoReflect() protoreflect.Message {
	mi := &file_media_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListActivity.ProtoReflect.Descriptor instead.
func (*ListActivity) Descriptor() ([]byte, []int) {
	return file_media_activity_proto_rawDescGZIP(), []int{0}
}

func (x *ListActivity) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ListActivity) GetCreatedAt() int32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *ListActivity) GetIsLiked() bool {
	if x != nil {
		return x.IsLiked
	}
	return false
}

func (x *ListActivity) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *ListActivity) GetProgress() string {
	if x != nil {
		return x.Progress
	}
	return ""
}

func (x *ListActivity) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListActivity) GetUser() *Viewer {
	if x != nil {
		return x.User
	}
	return nil
}

var File_media_activity_proto protoreflect.FileDescriptor

const file_media_activity_proto_rawDesc = "" +
	"\n" +
	"\x14media_activity.proto\x12\tgoodanime\x1a\fviewer.proto\"\xd2\x01\n" +
	"\fListActivity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x05R\tcreatedAt\x12\x19\n" +
	"\bis_liked\x18\x03 \x01(\bR\aisLiked\x12\x1d\n" +
	"\n" +
	"like_count\x18\x04 \x01(\x05R\tlikeCount\x12\x1a\n" +
	"\bprogress\x18\x05 \x01(\tR\bprogress\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12%\n" +
	"\x04user\x18\a \x01(\v2\x11.goodanime.ViewerR\x04userB\x19Z\x17goodanime/backend/protob\x06proto3"

var (
	file_media_activity_proto_rawDescOnce sync.Once
	file_media_activity_proto_rawDescData []byte
)

func file_media_activity_proto_rawDescGZIP() []byte {
	file_media_activity_proto_rawDescOnce.Do(func() {
		file_media_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_activity_proto_rawDesc), len(file_media_activity_proto_rawDesc)))
	})
	return file_media_activity_proto_rawDescData
}

var file_media_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_media_activity_proto_goTypes = []any{
	(*ListActivity)(nil), // 0: goodanime.ListActivity
	(*Viewer)(nil),       // 1: goodanime.Viewer
}
var file_media_activity_proto_depIdxs = []int32{
	1, // 0: goodanime.ListActivity.user:type_name -> goodanime.Viewer
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_media_activity_proto_init() }
func file_media_activity_proto_init() {
	if File_media_activity_proto != nil {
		return
	}
	file_viewer_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_activity_proto_rawDesc), len(file_media_activity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_media_activity_proto_goTypes,
		DependencyIndexes: file_media_activity_proto_depIdxs,
		MessageInfos:      file_media_activity_proto_msgTypes,
	}.Build()
	File_media_activity_proto = out.File
	file_media_activity_proto_goTypes = nil
	file_media_activity_proto_depIdxs = nil
}
