// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/medialist.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FuzzyDate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Day           int32                  `protobuf:"varint,1,opt,name=day,proto3" json:"day,omitempty"`
	Month         int32                  `protobuf:"varint,2,opt,name=month,proto3" json:"month,omitempty"`
	Year          int32                  `protobuf:"varint,3,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FuzzyDate) Reset() {
	*x = FuzzyDate{}
	mi := &file_proto_medialist_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FuzzyDate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuzzyDate) ProtoMessage() {}

func (x *FuzzyDate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medialist_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuzzyDate.ProtoReflect.Descriptor instead.
func (*FuzzyDate) Descriptor() ([]byte, []int) {
	return file_proto_medialist_proto_rawDescGZIP(), []int{0}
}

func (x *FuzzyDate) GetDay() int32 {
	if x != nil {
		return x.Day
	}
	return 0
}

func (x *FuzzyDate) GetMonth() int32 {
	if x != nil {
		return x.Month
	}
	return 0
}

func (x *FuzzyDate) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

type Trailer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Site          string                 `protobuf:"bytes,2,opt,name=site,proto3" json:"site,omitempty"`
	Thumbnail     string                 `protobuf:"bytes,3,opt,name=thumbnail,proto3" json:"thumbnail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Trailer) Reset() {
	*x = Trailer{}
	mi := &file_proto_medialist_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trailer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trailer) ProtoMessage() {}

func (x *Trailer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medialist_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trailer.ProtoReflect.Descriptor instead.
func (*Trailer) Descriptor() ([]byte, []int) {
	return file_proto_medialist_proto_rawDescGZIP(), []int{1}
}

func (x *Trailer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Trailer) GetSite() string {
	if x != nil {
		return x.Site
	}
	return ""
}

func (x *Trailer) GetThumbnail() string {
	if x != nil {
		return x.Thumbnail
	}
	return ""
}

type CoverImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Medium        string                 `protobuf:"bytes,1,opt,name=medium,proto3" json:"medium,omitempty"`
	Large         string                 `protobuf:"bytes,2,opt,name=large,proto3" json:"large,omitempty"`
	ExtraLarge    string                 `protobuf:"bytes,3,opt,name=extra_large,json=extraLarge,proto3" json:"extra_large,omitempty"`
	Color         string                 `protobuf:"bytes,4,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoverImage) Reset() {
	*x = CoverImage{}
	mi := &file_proto_medialist_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoverImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoverImage) ProtoMessage() {}

func (x *CoverImage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medialist_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoverImage.ProtoReflect.Descriptor instead.
func (*CoverImage) Descriptor() ([]byte, []int) {
	return file_proto_medialist_proto_rawDescGZIP(), []int{2}
}

func (x *CoverImage) GetMedium() string {
	if x != nil {
		return x.Medium
	}
	return ""
}

func (x *CoverImage) GetLarge() string {
	if x != nil {
		return x.Large
	}
	return ""
}

func (x *CoverImage) GetExtraLarge() string {
	if x != nil {
		return x.ExtraLarge
	}
	return ""
}

func (x *CoverImage) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type Title struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	English       string                 `protobuf:"bytes,1,opt,name=english,proto3" json:"english,omitempty"`
	Native        string                 `protobuf:"bytes,2,opt,name=native,proto3" json:"native,omitempty"`
	Romaji        string                 `protobuf:"bytes,3,opt,name=romaji,proto3" json:"romaji,omitempty"`
	UserPreferred string                 `protobuf:"bytes,4,opt,name=user_preferred,json=userPreferred,proto3" json:"user_preferred,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Title) Reset() {
	*x = Title{}
	mi := &file_proto_medialist_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Title) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Title) ProtoMessage() {}

func (x *Title) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medialist_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Title.ProtoReflect.Descriptor instead.
func (*Title) Descriptor() ([]byte, []int) {
	return file_proto_medialist_proto_rawDescGZIP(), []int{3}
}

func (x *Title) GetEnglish() string {
	if x != nil {
		return x.English
	}
	return ""
}

func (x *Title) GetNative() string {
	if x != nil {
		return x.Native
	}
	return ""
}

func (x *Title) GetRomaji() string {
	if x != nil {
		return x.Romaji
	}
	return ""
}

func (x *Title) GetUserPreferred() string {
	if x != nil {
		return x.UserPreferred
	}
	return ""
}

type Media struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         *Title                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	AverageScore  int32                  `protobuf:"varint,3,opt,name=average_score,json=averageScore,proto3" json:"average_score,omitempty"`
	BannerImage   string                 `protobuf:"bytes,4,opt,name=banner_image,json=bannerImage,proto3" json:"banner_image,omitempty"`
	CoverImage    *CoverImage            `protobuf:"bytes,5,opt,name=cover_image,json=coverImage,proto3" json:"cover_image,omitempty"`
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Duration      int32                  `protobuf:"varint,7,opt,name=duration,proto3" json:"duration,omitempty"`
	Episodes      int32                  `protobuf:"varint,8,opt,name=episodes,proto3" json:"episodes,omitempty"`
	Format        string                 `protobuf:"bytes,9,opt,name=format,proto3" json:"format,omitempty"`
	Genres        []string               `protobuf:"bytes,10,rep,name=genres,proto3" json:"genres,omitempty"`
	IsAdult       bool                   `protobuf:"varint,11,opt,name=is_adult,json=isAdult,proto3" json:"is_adult,omitempty"`
	IsFavourite   bool                   `protobuf:"varint,12,opt,name=is_favourite,json=isFavourite,proto3" json:"is_favourite,omitempty"`
	Popularity    int32                  `protobuf:"varint,13,opt,name=popularity,proto3" json:"popularity,omitempty"`
	Season        string                 `protobuf:"bytes,14,opt,name=season,proto3" json:"season,omitempty"`
	SeasonYear    int32                  `protobuf:"varint,15,opt,name=season_year,json=seasonYear,proto3" json:"season_year,omitempty"`
	Status        string                 `protobuf:"bytes,16,opt,name=status,proto3" json:"status,omitempty"`
	Trailer       *Trailer               `protobuf:"bytes,17,opt,name=trailer,proto3" json:"trailer,omitempty"`
	Synonyms      []string               `protobuf:"bytes,18,rep,name=synonyms,proto3" json:"synonyms,omitempty"`
	StartDate     *FuzzyDate             `protobuf:"bytes,19,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       *FuzzyDate             `protobuf:"bytes,20,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	MeanScore     int32                  `protobuf:"varint,21,opt,name=mean_score,json=meanScore,proto3" json:"mean_score,omitempty"`
	Favourites    int32                  `protobuf:"varint,22,opt,name=favourites,proto3" json:"favourites,omitempty"`
	SiteUrl       string                 `protobuf:"bytes,23,opt,name=site_url,json=siteUrl,proto3" json:"site_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_proto_medialist_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medialist_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_proto_medialist_proto_rawDescGZIP(), []int{4}
}

func (x *Media) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Media) GetTitle() *Title {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *Media) GetAverageScore() int32 {
	if x != nil {
		return x.AverageScore
	}
	return 0
}

func (x *Media) GetBannerImage() string {
	if x != nil {
		return x.BannerImage
	}
	return ""
}

func (x *Media) GetCoverImage() *CoverImage {
	if x != nil {
		return x.CoverImage
	}
	return nil
}

func (x *Media) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Media) GetDuration() int32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *Media) GetEpisodes() int32 {
	if x != nil {
		return x.Episodes
	}
	return 0
}

func (x *Media) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *Media) GetGenres() []string {
	if x != nil {
		return x.Genres
	}
	return nil
}

func (x *Media) GetIsAdult() bool {
	if x != nil {
		return x.IsAdult
	}
	return false
}

func (x *Media) GetIsFavourite() bool {
	if x != nil {
		return x.IsFavourite
	}
	return false
}

func (x *Media) GetPopularity() int32 {
	if x != nil {
		return x.Popularity
	}
	return 0
}

func (x *Media) GetSeason() string {
	if x != nil {
		return x.Season
	}
	return ""
}

func (x *Media) GetSeasonYear() int32 {
	if x != nil {
		return x.SeasonYear
	}
	return 0
}

func (x *Media) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Media) GetTrailer() *Trailer {
	if x != nil {
		return x.Trailer
	}
	return nil
}

func (x *Media) GetSynonyms() []string {
	if x != nil {
		return x.Synonyms
	}
	return nil
}

func (x *Media) GetStartDate() *FuzzyDate {
	if x != nil {
		return x.StartDate
	}
	return nil
}

func (x *Media) GetEndDate() *FuzzyDate {
	if x != nil {
		return x.EndDate
	}
	return nil
}

func (x *Media) GetMeanScore() int32 {
	if x != nil {
		return x.MeanScore
	}
	return 0
}

func (x *Media) GetFavourites() int32 {
	if x != nil {
		return x.Favourites
	}
	return 0
}

func (x *Media) GetSiteUrl() string {
	if x != nil {
		return x.SiteUrl
	}
	return ""
}

type MediaListEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Media         *Media                 `protobuf:"bytes,1,opt,name=media,proto3" json:"media,omitempty"`
	Progress      int32                  `protobuf:"varint,2,opt,name=progress,proto3" json:"progress,omitempty"`
	Repeat        int32                  `protobuf:"varint,3,opt,name=repeat,proto3" json:"repeat,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Score         float64                `protobuf:"fixed64,5,opt,name=score,proto3" json:"score,omitempty"`
	StartedAt     *FuzzyDate             `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *FuzzyDate             `protobuf:"bytes,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaListEntry) Reset() {
	*x = MediaListEntry{}
	mi := &file_proto_medialist_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaListEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaListEntry) ProtoMessage() {}

func (x *MediaListEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medialist_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaListEntry.ProtoReflect.Descriptor instead.
func (*MediaListEntry) Descriptor() ([]byte, []int) {
	return file_proto_medialist_proto_rawDescGZIP(), []int{5}
}

func (x *MediaListEntry) GetMedia() *Media {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *MediaListEntry) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *MediaListEntry) GetRepeat() int32 {
	if x != nil {
		return x.Repeat
	}
	return 0
}

func (x *MediaListEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MediaListEntry) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *MediaListEntry) GetStartedAt() *FuzzyDate {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *MediaListEntry) GetCompletedAt() *FuzzyDate {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type MediaList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Entries       []*MediaListEntry      `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaList) Reset() {
	*x = MediaList{}
	mi := &file_proto_medialist_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaList) ProtoMessage() {}

func (x *MediaList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medialist_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaList.ProtoReflect.Descriptor instead.
func (*MediaList) Descriptor() ([]byte, []int) {
	return file_proto_medialist_proto_rawDescGZIP(), []int{6}
}

func (x *MediaList) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MediaList) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *MediaList) GetEntries() []*MediaListEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type MediaListCollection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasNextChunk  bool                   `protobuf:"varint,1,opt,name=has_next_chunk,json=hasNextChunk,proto3" json:"has_next_chunk,omitempty"`
	Lists         []*MediaList           `protobuf:"bytes,2,rep,name=lists,proto3" json:"lists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaListCollection) Reset() {
	*x = MediaListCollection{}
	mi := &file_proto_medialist_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaListCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaListCollection) ProtoMessage() {}

func (x *MediaListCollection) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medialist_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaListCollection.ProtoReflect.Descriptor instead.
func (*MediaListCollection) Descriptor() ([]byte, []int) {
	return file_proto_medialist_proto_rawDescGZIP(), []int{7}
}

func (x *MediaListCollection) GetHasNextChunk() bool {
	if x != nil {
		return x.HasNextChunk
	}
	return false
}

func (x *MediaListCollection) GetLists() []*MediaList {
	if x != nil {
		return x.Lists
	}
	return nil
}

type FetchMediaListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int32                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Sort          []string               `protobuf:"bytes,3,rep,name=sort,proto3" json:"sort,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMediaListRequest) Reset() {
	*x = FetchMediaListRequest{}
	mi := &file_proto_medialist_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMediaListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMediaListRequest) ProtoMessage() {}

func (x *FetchMediaListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medialist_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMediaListRequest.ProtoReflect.Descriptor instead.
func (*FetchMediaListRequest) Descriptor() ([]byte, []int) {
	return file_proto_medialist_proto_rawDescGZIP(), []int{8}
}

func (x *FetchMediaListRequest) GetUserId() int32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *FetchMediaListRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FetchMediaListRequest) GetSort() []string {
	if x != nil {
		return x.Sort
	}
	return nil
}

type FetchMediaListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    *MediaListCollection   `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMediaListResponse) Reset() {
	*x = FetchMediaListResponse{}
	mi := &file_proto_medialist_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMediaListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMediaListResponse) ProtoMessage() {}

func (x *FetchMediaListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medialist_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMediaListResponse.ProtoReflect.Descriptor instead.
func (*FetchMediaListResponse) Descriptor() ([]byte, []int) {
	return file_proto_medialist_proto_rawDescGZIP(), []int{9}
}

func (x *FetchMediaListResponse) GetCollection() *MediaListCollection {
	if x != nil {
		return x.Collection
	}
	return nil
}

func (x *FetchMediaListResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Viewer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AvatarMedium  string                 `protobuf:"bytes,3,opt,name=avatar_medium,json=avatarMedium,proto3" json:"avatar_medium,omitempty"`
	CreatedAt     int32                  `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Viewer) Reset() {
	*x = Viewer{}
	mi := &file_proto_medialist_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Viewer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Viewer) ProtoMessage() {}

func (x *Viewer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medialist_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Viewer.ProtoReflect.Descriptor instead.
func (*Viewer) Descriptor() ([]byte, []int) {
	return file_proto_medialist_proto_rawDescGZIP(), []int{10}
}

func (x *Viewer) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Viewer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Viewer) GetAvatarMedium() string {
	if x != nil {
		return x.AvatarMedium
	}
	return ""
}

func (x *Viewer) GetCreatedAt() int32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type FetchViewerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Viewer        *Viewer                `protobuf:"bytes,1,opt,name=viewer,proto3" json:"viewer,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchViewerResponse) Reset() {
	*x = FetchViewerResponse{}
	mi := &file_proto_medialist_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchViewerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchViewerResponse) ProtoMessage() {}

func (x *FetchViewerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medialist_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchViewerResponse.ProtoReflect.Descriptor instead.
func (*FetchViewerResponse) Descriptor() ([]byte, []int) {
	return file_proto_medialist_proto_rawDescGZIP(), []int{11}
}

func (x *FetchViewerResponse) GetViewer() *Viewer {
	if x != nil {
		return x.Viewer
	}
	return nil
}

func (x *FetchViewerResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FuzzyDateInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Year          *int32                 `protobuf:"varint,1,opt,name=year,proto3,oneof" json:"year,omitempty"`
	Month         *int32                 `protobuf:"varint,2,opt,name=month,proto3,oneof" json:"month,omitempty"`
	Day           *int32                 `protobuf:"varint,3,opt,name=day,proto3,oneof" json:"day,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FuzzyDateInput) Reset() {
	*x = FuzzyDateInput{}
	mi := &file_proto_medialist_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FuzzyDateInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuzzyDateInput) ProtoMessage() {}

func (x *FuzzyDateInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medialist_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuzzyDateInput.ProtoReflect.Descriptor instead.
func (*FuzzyDateInput) Descriptor() ([]byte, []int) {
	return file_proto_medialist_proto_rawDescGZIP(), []int{12}
}

func (x *FuzzyDateInput) GetYear() int32 {
	if x != nil && x.Year != nil {
		return *x.Year
	}
	return 0
}

func (x *FuzzyDateInput) GetMonth() int32 {
	if x != nil && x.Month != nil {
		return *x.Month
	}
	return 0
}

func (x *FuzzyDateInput) GetDay() int32 {
	if x != nil && x.Day != nil {
		return *x.Day
	}
	return 0
}

type SaveMediaListEntryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       int32                  `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Progress      *int32                 `protobuf:"varint,2,opt,name=progress,proto3,oneof" json:"progress,omitempty"`
	Status        *string                `protobuf:"bytes,3,opt,name=status,proto3,oneof" json:"status,omitempty"`
	Score         *float64               `protobuf:"fixed64,4,opt,name=score,proto3,oneof" json:"score,omitempty"`
	StartedAt     *FuzzyDateInput        `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3,oneof" json:"started_at,omitempty"`
	CompletedAt   *FuzzyDateInput        `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveMediaListEntryRequest) Reset() {
	*x = SaveMediaListEntryRequest{}
	mi := &file_proto_medialist_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveMediaListEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMediaListEntryRequest) ProtoMessage() {}

func (x *SaveMediaListEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medialist_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMediaListEntryRequest.ProtoReflect.Descriptor instead.
func (*SaveMediaListEntryRequest) Descriptor() ([]byte, []int) {
	return file_proto_medialist_proto_rawDescGZIP(), []int{13}
}

func (x *SaveMediaListEntryRequest) GetMediaId() int32 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *SaveMediaListEntryRequest) GetProgress() int32 {
	if x != nil && x.Progress != nil {
		return *x.Progress
	}
	return 0
}

func (x *SaveMediaListEntryRequest) GetStatus() string {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return ""
}

func (x *SaveMediaListEntryRequest) GetScore() float64 {
	if x != nil && x.Score != nil {
		return *x.Score
	}
	return 0
}

func (x *SaveMediaListEntryRequest) GetStartedAt() *FuzzyDateInput {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *SaveMediaListEntryRequest) GetCompletedAt() *FuzzyDateInput {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

type SaveMediaListEntryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Progress      int32                  `protobuf:"varint,3,opt,name=progress,proto3" json:"progress,omitempty"`
	Score         float64                `protobuf:"fixed64,4,opt,name=score,proto3" json:"score,omitempty"`
	Repeat        int32                  `protobuf:"varint,5,opt,name=repeat,proto3" json:"repeat,omitempty"`
	StartedAt     *FuzzyDate             `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   *FuzzyDate             `protobuf:"bytes,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveMediaListEntryResponse) Reset() {
	*x = SaveMediaListEntryResponse{}
	mi := &file_proto_medialist_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveMediaListEntryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveMediaListEntryResponse) ProtoMessage() {}

func (x *SaveMediaListEntryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medialist_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveMediaListEntryResponse.ProtoReflect.Descriptor instead.
func (*SaveMediaListEntryResponse) Descriptor() ([]byte, []int) {
	return file_proto_medialist_proto_rawDescGZIP(), []int{14}
}

func (x *SaveMediaListEntryResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SaveMediaListEntryResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *SaveMediaListEntryResponse) GetProgress() int32 {
	if x != nil {
		return x.Progress
	}
	return 0
}

func (x *SaveMediaListEntryResponse) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *SaveMediaListEntryResponse) GetRepeat() int32 {
	if x != nil {
		return x.Repeat
	}
	return 0
}

func (x *SaveMediaListEntryResponse) GetStartedAt() *FuzzyDate {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *SaveMediaListEntryResponse) GetCompletedAt() *FuzzyDate {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *SaveMediaListEntryResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FetchMediaDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       int32                  `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMediaDetailsRequest) Reset() {
	*x = FetchMediaDetailsRequest{}
	mi := &file_proto_medialist_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMediaDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMediaDetailsRequest) ProtoMessage() {}

func (x *FetchMediaDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medialist_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMediaDetailsRequest.ProtoReflect.Descriptor instead.
func (*FetchMediaDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_medialist_proto_rawDescGZIP(), []int{15}
}

func (x *FetchMediaDetailsRequest) GetMediaId() int32 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

type FetchMediaDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawJson       string                 `protobuf:"bytes,1,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMediaDetailsResponse) Reset() {
	*x = FetchMediaDetailsResponse{}
	mi := &file_proto_medialist_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMediaDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMediaDetailsResponse) ProtoMessage() {}

func (x *FetchMediaDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medialist_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMediaDetailsResponse.ProtoReflect.Descriptor instead.
func (*FetchMediaDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_medialist_proto_rawDescGZIP(), []int{16}
}

func (x *FetchMediaDetailsResponse) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

func (x *FetchMediaDetailsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FetchMediaStaffRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       int32                  `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,3,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMediaStaffRequest) Reset() {
	*x = FetchMediaStaffRequest{}
	mi := &file_proto_medialist_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMediaStaffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMediaStaffRequest) ProtoMessage() {}

func (x *FetchMediaStaffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medialist_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMediaStaffRequest.ProtoReflect.Descriptor instead.
func (*FetchMediaStaffRequest) Descriptor() ([]byte, []int) {
	return file_proto_medialist_proto_rawDescGZIP(), []int{17}
}

func (x *FetchMediaStaffRequest) GetMediaId() int32 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *FetchMediaStaffRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FetchMediaStaffRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type FetchMediaStaffResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawJson       string                 `protobuf:"bytes,1,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMediaStaffResponse) Reset() {
	*x = FetchMediaStaffResponse{}
	mi := &file_proto_medialist_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMediaStaffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMediaStaffResponse) ProtoMessage() {}

func (x *FetchMediaStaffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medialist_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMediaStaffResponse.ProtoReflect.Descriptor instead.
func (*FetchMediaStaffResponse) Descriptor() ([]byte, []int) {
	return file_proto_medialist_proto_rawDescGZIP(), []int{18}
}

func (x *FetchMediaStaffResponse) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

func (x *FetchMediaStaffResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FetchMediaCharactersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       int32                  `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,3,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMediaCharactersRequest) Reset() {
	*x = FetchMediaCharactersRequest{}
	mi := &file_proto_medialist_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMediaCharactersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMediaCharactersRequest) ProtoMessage() {}

func (x *FetchMediaCharactersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medialist_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMediaCharactersRequest.ProtoReflect.Descriptor instead.
func (*FetchMediaCharactersRequest) Descriptor() ([]byte, []int) {
	return file_proto_medialist_proto_rawDescGZIP(), []int{19}
}

func (x *FetchMediaCharactersRequest) GetMediaId() int32 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *FetchMediaCharactersRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FetchMediaCharactersRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type FetchMediaCharactersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawJson       string                 `protobuf:"bytes,1,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMediaCharactersResponse) Reset() {
	*x = FetchMediaCharactersResponse{}
	mi := &file_proto_medialist_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMediaCharactersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMediaCharactersResponse) ProtoMessage() {}

func (x *FetchMediaCharactersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medialist_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMediaCharactersResponse.ProtoReflect.Descriptor instead.
func (*FetchMediaCharactersResponse) Descriptor() ([]byte, []int) {
	return file_proto_medialist_proto_rawDescGZIP(), []int{20}
}

func (x *FetchMediaCharactersResponse) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

func (x *FetchMediaCharactersResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type FetchMediaRecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MediaId       int32                  `protobuf:"varint,1,opt,name=media_id,json=mediaId,proto3" json:"media_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,3,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMediaRecommendationsRequest) Reset() {
	*x = FetchMediaRecommendationsRequest{}
	mi := &file_proto_medialist_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMediaRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMediaRecommendationsRequest) ProtoMessage() {}

func (x *FetchMediaRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medialist_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMediaRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*FetchMediaRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_proto_medialist_proto_rawDescGZIP(), []int{21}
}

func (x *FetchMediaRecommendationsRequest) GetMediaId() int32 {
	if x != nil {
		return x.MediaId
	}
	return 0
}

func (x *FetchMediaRecommendationsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *FetchMediaRecommendationsRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type FetchMediaRecommendationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RawJson       string                 `protobuf:"bytes,1,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchMediaRecommendationsResponse) Reset() {
	*x = FetchMediaRecommendationsResponse{}
	mi := &file_proto_medialist_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchMediaRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchMediaRecommendationsResponse) ProtoMessage() {}

func (x *FetchMediaRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medialist_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchMediaRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*FetchMediaRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_proto_medialist_proto_rawDescGZIP(), []int{22}
}

func (x *FetchMediaRecommendationsResponse) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

func (x *FetchMediaRecommendationsResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ToggleFavouriteAnimeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnimeId       int32                  `protobuf:"varint,1,opt,name=animeId,proto3" json:"animeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleFavouriteAnimeRequest) Reset() {
	*x = ToggleFavouriteAnimeRequest{}
	mi := &file_proto_medialist_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleFavouriteAnimeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleFavouriteAnimeRequest) ProtoMessage() {}

func (x *ToggleFavouriteAnimeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medialist_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleFavouriteAnimeRequest.ProtoReflect.Descriptor instead.
func (*ToggleFavouriteAnimeRequest) Descriptor() ([]byte, []int) {
	return file_proto_medialist_proto_rawDescGZIP(), []int{23}
}

func (x *ToggleFavouriteAnimeRequest) GetAnimeId() int32 {
	if x != nil {
		return x.AnimeId
	}
	return 0
}

type ToggleFavouriteAnimeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnimeId       int32                  `protobuf:"varint,1,opt,name=animeId,proto3" json:"animeId,omitempty"`
	IsFavourite   bool                   `protobuf:"varint,2,opt,name=isFavourite,proto3" json:"isFavourite,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleFavouriteAnimeResponse) Reset() {
	*x = ToggleFavouriteAnimeResponse{}
	mi := &file_proto_medialist_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleFavouriteAnimeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleFavouriteAnimeResponse) ProtoMessage() {}

func (x *ToggleFavouriteAnimeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_medialist_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleFavouriteAnimeResponse.ProtoReflect.Descriptor instead.
func (*ToggleFavouriteAnimeResponse) Descriptor() ([]byte, []int) {
	return file_proto_medialist_proto_rawDescGZIP(), []int{24}
}

func (x *ToggleFavouriteAnimeResponse) GetAnimeId() int32 {
	if x != nil {
		return x.AnimeId
	}
	return 0
}

func (x *ToggleFavouriteAnimeResponse) GetIsFavourite() bool {
	if x != nil {
		return x.IsFavourite
	}
	return false
}

func (x *ToggleFavouriteAnimeResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_medialist_proto protoreflect.FileDescriptor

const file_proto_medialist_proto_rawDesc = "" +
	"\n" +
	"\x15proto/medialist.proto\x12\tgoodanime\"G\n" +
	"\tFuzzyDate\x12\x10\n" +
	"\x03day\x18\x01 \x01(\x05R\x03day\x12\x14\n" +
	"\x05month\x18\x02 \x01(\x05R\x05month\x12\x12\n" +
	"\x04year\x18\x03 \x01(\x05R\x04year\"K\n" +
	"\aTrailer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04site\x18\x02 \x01(\tR\x04site\x12\x1c\n" +
	"\tthumbnail\x18\x03 \x01(\tR\tthumbnail\"q\n" +
	"\n" +
	"CoverImage\x12\x16\n" +
	"\x06medium\x18\x01 \x01(\tR\x06medium\x12\x14\n" +
	"\x05large\x18\x02 \x01(\tR\x05large\x12\x1f\n" +
	"\vextra_large\x18\x03 \x01(\tR\n" +
	"extraLarge\x12\x14\n" +
	"\x05color\x18\x04 \x01(\tR\x05color\"x\n" +
	"\x05Title\x12\x18\n" +
	"\aenglish\x18\x01 \x01(\tR\aenglish\x12\x16\n" +
	"\x06native\x18\x02 \x01(\tR\x06native\x12\x16\n" +
	"\x06romaji\x18\x03 \x01(\tR\x06romaji\x12%\n" +
	"\x0euser_preferred\x18\x04 \x01(\tR\ruserPreferred\"\x82\x06\n" +
	"\x05Media\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12&\n" +
	"\x05title\x18\x02 \x01(\v2\x10.goodanime.TitleR\x05title\x12#\n" +
	"\raverage_score\x18\x03 \x01(\x05R\faverageScore\x12!\n" +
	"\fbanner_image\x18\x04 \x01(\tR\vbannerImage\x126\n" +
	"\vcover_image\x18\x05 \x01(\v2\x15.goodanime.CoverImageR\n" +
	"coverImage\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1a\n" +
	"\bduration\x18\a \x01(\x05R\bduration\x12\x1a\n" +
	"\bepisodes\x18\b \x01(\x05R\bepisodes\x12\x16\n" +
	"\x06format\x18\t \x01(\tR\x06format\x12\x16\n" +
	"\x06genres\x18\n" +
	" \x03(\tR\x06genres\x12\x19\n" +
	"\bis_adult\x18\v \x01(\bR\aisAdult\x12!\n" +
	"\fis_favourite\x18\f \x01(\bR\visFavourite\x12\x1e\n" +
	"\n" +
	"popularity\x18\r \x01(\x05R\n" +
	"popularity\x12\x16\n" +
	"\x06season\x18\x0e \x01(\tR\x06season\x12\x1f\n" +
	"\vseason_year\x18\x0f \x01(\x05R\n" +
	"seasonYear\x12\x16\n" +
	"\x06status\x18\x10 \x01(\tR\x06status\x12,\n" +
	"\atrailer\x18\x11 \x01(\v2\x12.goodanime.TrailerR\atrailer\x12\x1a\n" +
	"\bsynonyms\x18\x12 \x03(\tR\bsynonyms\x123\n" +
	"\n" +
	"start_date\x18\x13 \x01(\v2\x14.goodanime.FuzzyDateR\tstartDate\x12/\n" +
	"\bend_date\x18\x14 \x01(\v2\x14.goodanime.FuzzyDateR\aendDate\x12\x1d\n" +
	"\n" +
	"mean_score\x18\x15 \x01(\x05R\tmeanScore\x12\x1e\n" +
	"\n" +
	"favourites\x18\x16 \x01(\x05R\n" +
	"favourites\x12\x19\n" +
	"\bsite_url\x18\x17 \x01(\tR\asiteUrl\"\x88\x02\n" +
	"\x0eMediaListEntry\x12&\n" +
	"\x05media\x18\x01 \x01(\v2\x10.goodanime.MediaR\x05media\x12\x1a\n" +
	"\bprogress\x18\x02 \x01(\x05R\bprogress\x12\x16\n" +
	"\x06repeat\x18\x03 \x01(\x05R\x06repeat\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x14\n" +
	"\x05score\x18\x05 \x01(\x01R\x05score\x123\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x14.goodanime.FuzzyDateR\tstartedAt\x127\n" +
	"\fcompleted_at\x18\a \x01(\v2\x14.goodanime.FuzzyDateR\vcompletedAt\"l\n" +
	"\tMediaList\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x123\n" +
	"\aentries\x18\x03 \x03(\v2\x19.goodanime.MediaListEntryR\aentries\"g\n" +
	"\x13MediaListCollection\x12$\n" +
	"\x0ehas_next_chunk\x18\x01 \x01(\bR\fhasNextChunk\x12*\n" +
	"\x05lists\x18\x02 \x03(\v2\x14.goodanime.MediaListR\x05lists\"X\n" +
	"\x15FetchMediaListRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x05R\x06userId\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04sort\x18\x03 \x03(\tR\x04sort\"n\n" +
	"\x16FetchMediaListResponse\x12>\n" +
	"\n" +
	"collection\x18\x01 \x01(\v2\x1e.goodanime.MediaListCollectionR\n" +
	"collection\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"p\n" +
	"\x06Viewer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\ravatar_medium\x18\x03 \x01(\tR\favatarMedium\x12\x1d\n" +
	"\n" +
	"created_at\x18\x04 \x01(\x05R\tcreatedAt\"V\n" +
	"\x13FetchViewerResponse\x12)\n" +
	"\x06viewer\x18\x01 \x01(\v2\x11.goodanime.ViewerR\x06viewer\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"v\n" +
	"\x0eFuzzyDateInput\x12\x17\n" +
	"\x04year\x18\x01 \x01(\x05H\x00R\x04year\x88\x01\x01\x12\x19\n" +
	"\x05month\x18\x02 \x01(\x05H\x01R\x05month\x88\x01\x01\x12\x15\n" +
	"\x03day\x18\x03 \x01(\x05H\x02R\x03day\x88\x01\x01B\a\n" +
	"\x05_yearB\b\n" +
	"\x06_monthB\x06\n" +
	"\x04_day\"\xd3\x02\n" +
	"\x19SaveMediaListEntryRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\x05R\amediaId\x12\x1f\n" +
	"\bprogress\x18\x02 \x01(\x05H\x00R\bprogress\x88\x01\x01\x12\x1b\n" +
	"\x06status\x18\x03 \x01(\tH\x01R\x06status\x88\x01\x01\x12\x19\n" +
	"\x05score\x18\x04 \x01(\x01H\x02R\x05score\x88\x01\x01\x12=\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x19.goodanime.FuzzyDateInputH\x03R\tstartedAt\x88\x01\x01\x12A\n" +
	"\fcompleted_at\x18\x06 \x01(\v2\x19.goodanime.FuzzyDateInputH\x04R\vcompletedAt\x88\x01\x01B\v\n" +
	"\t_progressB\t\n" +
	"\a_statusB\b\n" +
	"\x06_scoreB\r\n" +
	"\v_started_atB\x0f\n" +
	"\r_completed_at\"\x92\x02\n" +
	"\x1aSaveMediaListEntryResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1a\n" +
	"\bprogress\x18\x03 \x01(\x05R\bprogress\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x01R\x05score\x12\x16\n" +
	"\x06repeat\x18\x05 \x01(\x05R\x06repeat\x123\n" +
	"\n" +
	"started_at\x18\x06 \x01(\v2\x14.goodanime.FuzzyDateR\tstartedAt\x127\n" +
	"\fcompleted_at\x18\a \x01(\v2\x14.goodanime.FuzzyDateR\vcompletedAt\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\"5\n" +
	"\x18FetchMediaDetailsRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\x05R\amediaId\"L\n" +
	"\x19FetchMediaDetailsResponse\x12\x19\n" +
	"\braw_json\x18\x01 \x01(\tR\arawJson\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"b\n" +
	"\x16FetchMediaStaffRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\x05R\amediaId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x03 \x01(\x05R\aperPage\"J\n" +
	"\x17FetchMediaStaffResponse\x12\x19\n" +
	"\braw_json\x18\x01 \x01(\tR\arawJson\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"g\n" +
	"\x1bFetchMediaCharactersRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\x05R\amediaId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x03 \x01(\x05R\aperPage\"O\n" +
	"\x1cFetchMediaCharactersResponse\x12\x19\n" +
	"\braw_json\x18\x01 \x01(\tR\arawJson\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"l\n" +
	" FetchMediaRecommendationsRequest\x12\x19\n" +
	"\bmedia_id\x18\x01 \x01(\x05R\amediaId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x03 \x01(\x05R\aperPage\"T\n" +
	"!FetchMediaRecommendationsResponse\x12\x19\n" +
	"\braw_json\x18\x01 \x01(\tR\arawJson\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"7\n" +
	"\x1bToggleFavouriteAnimeRequest\x12\x18\n" +
	"\aanimeId\x18\x01 \x01(\x05R\aanimeId\"p\n" +
	"\x1cToggleFavouriteAnimeResponse\x12\x18\n" +
	"\aanimeId\x18\x01 \x01(\x05R\aanimeId\x12 \n" +
	"\visFavourite\x18\x02 \x01(\bR\visFavourite\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05errorB\x19Z\x17goodanime/backend/protob\x06proto3"

var (
	file_proto_medialist_proto_rawDescOnce sync.Once
	file_proto_medialist_proto_rawDescData []byte
)

func file_proto_medialist_proto_rawDescGZIP() []byte {
	file_proto_medialist_proto_rawDescOnce.Do(func() {
		file_proto_medialist_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_medialist_proto_rawDesc), len(file_proto_medialist_proto_rawDesc)))
	})
	return file_proto_medialist_proto_rawDescData
}

var file_proto_medialist_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_proto_medialist_proto_goTypes = []any{
	(*FuzzyDate)(nil),                         // 0: goodanime.FuzzyDate
	(*Trailer)(nil),                           // 1: goodanime.Trailer
	(*CoverImage)(nil),                        // 2: goodanime.CoverImage
	(*Title)(nil),                             // 3: goodanime.Title
	(*Media)(nil),                             // 4: goodanime.Media
	(*MediaListEntry)(nil),                    // 5: goodanime.MediaListEntry
	(*MediaList)(nil),                         // 6: goodanime.MediaList
	(*MediaListCollection)(nil),               // 7: goodanime.MediaListCollection
	(*FetchMediaListRequest)(nil),             // 8: goodanime.FetchMediaListRequest
	(*FetchMediaListResponse)(nil),            // 9: goodanime.FetchMediaListResponse
	(*Viewer)(nil),                            // 10: goodanime.Viewer
	(*FetchViewerResponse)(nil),               // 11: goodanime.FetchViewerResponse
	(*FuzzyDateInput)(nil),                    // 12: goodanime.FuzzyDateInput
	(*SaveMediaListEntryRequest)(nil),         // 13: goodanime.SaveMediaListEntryRequest
	(*SaveMediaListEntryResponse)(nil),        // 14: goodanime.SaveMediaListEntryResponse
	(*FetchMediaDetailsRequest)(nil),          // 15: goodanime.FetchMediaDetailsRequest
	(*FetchMediaDetailsResponse)(nil),         // 16: goodanime.FetchMediaDetailsResponse
	(*FetchMediaStaffRequest)(nil),            // 17: goodanime.FetchMediaStaffRequest
	(*FetchMediaStaffResponse)(nil),           // 18: goodanime.FetchMediaStaffResponse
	(*FetchMediaCharactersRequest)(nil),       // 19: goodanime.FetchMediaCharactersRequest
	(*FetchMediaCharactersResponse)(nil),      // 20: goodanime.FetchMediaCharactersResponse
	(*FetchMediaRecommendationsRequest)(nil),  // 21: goodanime.FetchMediaRecommendationsRequest
	(*FetchMediaRecommendationsResponse)(nil), // 22: goodanime.FetchMediaRecommendationsResponse
	(*ToggleFavouriteAnimeRequest)(nil),       // 23: goodanime.ToggleFavouriteAnimeRequest
	(*ToggleFavouriteAnimeResponse)(nil),      // 24: goodanime.ToggleFavouriteAnimeResponse
}
var file_proto_medialist_proto_depIdxs = []int32{
	3,  // 0: goodanime.Media.title:type_name -> goodanime.Title
	2,  // 1: goodanime.Media.cover_image:type_name -> goodanime.CoverImage
	1,  // 2: goodanime.Media.trailer:type_name -> goodanime.Trailer
	0,  // 3: goodanime.Media.start_date:type_name -> goodanime.FuzzyDate
	0,  // 4: goodanime.Media.end_date:type_name -> goodanime.FuzzyDate
	4,  // 5: goodanime.MediaListEntry.media:type_name -> goodanime.Media
	0,  // 6: goodanime.MediaListEntry.started_at:type_name -> goodanime.FuzzyDate
	0,  // 7: goodanime.MediaListEntry.completed_at:type_name -> goodanime.FuzzyDate
	5,  // 8: goodanime.MediaList.entries:type_name -> goodanime.MediaListEntry
	6,  // 9: goodanime.MediaListCollection.lists:type_name -> goodanime.MediaList
	7,  // 10: goodanime.FetchMediaListResponse.collection:type_name -> goodanime.MediaListCollection
	10, // 11: goodanime.FetchViewerResponse.viewer:type_name -> goodanime.Viewer
	12, // 12: goodanime.SaveMediaListEntryRequest.started_at:type_name -> goodanime.FuzzyDateInput
	12, // 13: goodanime.SaveMediaListEntryRequest.completed_at:type_name -> goodanime.FuzzyDateInput
	0,  // 14: goodanime.SaveMediaListEntryResponse.started_at:type_name -> goodanime.FuzzyDate
	0,  // 15: goodanime.SaveMediaListEntryResponse.completed_at:type_name -> goodanime.FuzzyDate
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_medialist_proto_init() }
func file_proto_medialist_proto_init() {
	if File_proto_medialist_proto != nil {
		return
	}
	file_proto_medialist_proto_msgTypes[12].OneofWrappers = []any{}
	file_proto_medialist_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_medialist_proto_rawDesc), len(file_proto_medialist_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_medialist_proto_goTypes,
		DependencyIndexes: file_proto_medialist_proto_depIdxs,
		MessageInfos:      file_proto_medialist_proto_msgTypes,
	}.Build()
	File_proto_medialist_proto = out.File
	file_proto_medialist_proto_goTypes = nil
	file_proto_medialist_proto_depIdxs = nil
}
