// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: media_character.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CharacterName struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Full               string                 `protobuf:"bytes,1,opt,name=full,proto3" json:"full,omitempty"`
	Native             *string                `protobuf:"bytes,2,opt,name=native,proto3,oneof" json:"native,omitempty"`
	UserPreferred      *string                `protobuf:"bytes,3,opt,name=user_preferred,json=userPreferred,proto3,oneof" json:"user_preferred,omitempty"`
	Alternative        []string               `protobuf:"bytes,4,rep,name=alternative,proto3" json:"alternative,omitempty"`
	AlternativeSpoiler []string               `protobuf:"bytes,5,rep,name=alternative_spoiler,json=alternativeSpoiler,proto3" json:"alternative_spoiler,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CharacterName) Reset() {
	*x = CharacterName{}
	mi := &file_media_character_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterName) ProtoMessage() {}

func (x *CharacterName) ProtoReflect() protoreflect.Message {
	mi := &file_media_character_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterName.ProtoReflect.Descriptor instead.
func (*CharacterName) Descriptor() ([]byte, []int) {
	return file_media_character_proto_rawDescGZIP(), []int{0}
}

func (x *CharacterName) GetFull() string {
	if x != nil {
		return x.Full
	}
	return ""
}

func (x *CharacterName) GetNative() string {
	if x != nil && x.Native != nil {
		return *x.Native
	}
	return ""
}

func (x *CharacterName) GetUserPreferred() string {
	if x != nil && x.UserPreferred != nil {
		return *x.UserPreferred
	}
	return ""
}

func (x *CharacterName) GetAlternative() []string {
	if x != nil {
		return x.Alternative
	}
	return nil
}

func (x *CharacterName) GetAlternativeSpoiler() []string {
	if x != nil {
		return x.AlternativeSpoiler
	}
	return nil
}

type CharacterImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Large         *string                `protobuf:"bytes,1,opt,name=large,proto3,oneof" json:"large,omitempty"`
	Medium        *string                `protobuf:"bytes,2,opt,name=medium,proto3,oneof" json:"medium,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterImage) Reset() {
	*x = CharacterImage{}
	mi := &file_media_character_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterImage) ProtoMessage() {}

func (x *CharacterImage) ProtoReflect() protoreflect.Message {
	mi := &file_media_character_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterImage.ProtoReflect.Descriptor instead.
func (*CharacterImage) Descriptor() ([]byte, []int) {
	return file_media_character_proto_rawDescGZIP(), []int{1}
}

func (x *CharacterImage) GetLarge() string {
	if x != nil && x.Large != nil {
		return *x.Large
	}
	return ""
}

func (x *CharacterImage) GetMedium() string {
	if x != nil && x.Medium != nil {
		return *x.Medium
	}
	return ""
}

type CharacterMin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *CharacterName         `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         *CharacterImage        `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterMin) Reset() {
	*x = CharacterMin{}
	mi := &file_media_character_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterMin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterMin) ProtoMessage() {}

func (x *CharacterMin) ProtoReflect() protoreflect.Message {
	mi := &file_media_character_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterMin.ProtoReflect.Descriptor instead.
func (*CharacterMin) Descriptor() ([]byte, []int) {
	return file_media_character_proto_rawDescGZIP(), []int{2}
}

func (x *CharacterMin) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CharacterMin) GetName() *CharacterName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *CharacterMin) GetImage() *CharacterImage {
	if x != nil {
		return x.Image
	}
	return nil
}

type CharacterMediaEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CharacterRole *string                `protobuf:"bytes,1,opt,name=character_role,json=characterRole,proto3,oneof" json:"character_role,omitempty"`
	Node          *MediaMin              `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	VoiceActors   []*StaffMin            `protobuf:"bytes,3,rep,name=voice_actors,json=voiceActors,proto3" json:"voice_actors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterMediaEdge) Reset() {
	*x = CharacterMediaEdge{}
	mi := &file_media_character_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterMediaEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterMediaEdge) ProtoMessage() {}

func (x *CharacterMediaEdge) ProtoReflect() protoreflect.Message {
	mi := &file_media_character_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterMediaEdge.ProtoReflect.Descriptor instead.
func (*CharacterMediaEdge) Descriptor() ([]byte, []int) {
	return file_media_character_proto_rawDescGZIP(), []int{3}
}

func (x *CharacterMediaEdge) GetCharacterRole() string {
	if x != nil && x.CharacterRole != nil {
		return *x.CharacterRole
	}
	return ""
}

func (x *CharacterMediaEdge) GetNode() *MediaMin {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *CharacterMediaEdge) GetVoiceActors() []*StaffMin {
	if x != nil {
		return x.VoiceActors
	}
	return nil
}

type CharacterMediaConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edges         []*CharacterMediaEdge  `protobuf:"bytes,1,rep,name=edges,proto3" json:"edges,omitempty"`
	PageInfo      *PageInfo              `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterMediaConnection) Reset() {
	*x = CharacterMediaConnection{}
	mi := &file_media_character_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterMediaConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterMediaConnection) ProtoMessage() {}

func (x *CharacterMediaConnection) ProtoReflect() protoreflect.Message {
	mi := &file_media_character_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterMediaConnection.ProtoReflect.Descriptor instead.
func (*CharacterMediaConnection) Descriptor() ([]byte, []int) {
	return file_media_character_proto_rawDescGZIP(), []int{4}
}

func (x *CharacterMediaConnection) GetEdges() []*CharacterMediaEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *CharacterMediaConnection) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

type Character struct {
	state              protoimpl.MessageState    `protogen:"open.v1"`
	Name               *CharacterName            `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image              *CharacterImage           `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Gender             *string                   `protobuf:"bytes,3,opt,name=gender,proto3,oneof" json:"gender,omitempty"`
	Age                *string                   `protobuf:"bytes,4,opt,name=age,proto3,oneof" json:"age,omitempty"`
	DateOfBirth        *FuzzyDate                `protobuf:"bytes,5,opt,name=date_of_birth,json=dateOfBirth,proto3" json:"date_of_birth,omitempty"`
	Description        *string                   `protobuf:"bytes,6,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Id                 *int32                    `protobuf:"varint,7,opt,name=id,proto3,oneof" json:"id,omitempty"`
	BloodType          *string                   `protobuf:"bytes,8,opt,name=blood_type,json=bloodType,proto3,oneof" json:"blood_type,omitempty"`
	Favourites         *int32                    `protobuf:"varint,9,opt,name=favourites,proto3,oneof" json:"favourites,omitempty"`
	IsFavourite        *bool                     `protobuf:"varint,10,opt,name=is_favourite,json=isFavourite,proto3,oneof" json:"is_favourite,omitempty"`
	SiteUrl            *string                   `protobuf:"bytes,11,opt,name=site_url,json=siteUrl,proto3,oneof" json:"site_url,omitempty"`
	Media              *CharacterMediaConnection `protobuf:"bytes,12,opt,name=media,proto3" json:"media,omitempty"`
	IsFavouriteBlocked *bool                     `protobuf:"varint,13,opt,name=is_favourite_blocked,json=isFavouriteBlocked,proto3,oneof" json:"is_favourite_blocked,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Character) Reset() {
	*x = Character{}
	mi := &file_media_character_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Character) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Character) ProtoMessage() {}

func (x *Character) ProtoReflect() protoreflect.Message {
	mi := &file_media_character_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Character.ProtoReflect.Descriptor instead.
func (*Character) Descriptor() ([]byte, []int) {
	return file_media_character_proto_rawDescGZIP(), []int{5}
}

func (x *Character) GetName() *CharacterName {
	if x != nil {
		return x.Name
	}
	return nil
}

func (x *Character) GetImage() *CharacterImage {
	if x != nil {
		return x.Image
	}
	return nil
}

func (x *Character) GetGender() string {
	if x != nil && x.Gender != nil {
		return *x.Gender
	}
	return ""
}

func (x *Character) GetAge() string {
	if x != nil && x.Age != nil {
		return *x.Age
	}
	return ""
}

func (x *Character) GetDateOfBirth() *FuzzyDate {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *Character) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *Character) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *Character) GetBloodType() string {
	if x != nil && x.BloodType != nil {
		return *x.BloodType
	}
	return ""
}

func (x *Character) GetFavourites() int32 {
	if x != nil && x.Favourites != nil {
		return *x.Favourites
	}
	return 0
}

func (x *Character) GetIsFavourite() bool {
	if x != nil && x.IsFavourite != nil {
		return *x.IsFavourite
	}
	return false
}

func (x *Character) GetSiteUrl() string {
	if x != nil && x.SiteUrl != nil {
		return *x.SiteUrl
	}
	return ""
}

func (x *Character) GetMedia() *CharacterMediaConnection {
	if x != nil {
		return x.Media
	}
	return nil
}

func (x *Character) GetIsFavouriteBlocked() bool {
	if x != nil && x.IsFavouriteBlocked != nil {
		return *x.IsFavouriteBlocked
	}
	return false
}

type CharacterEdge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Node          *CharacterMin          `protobuf:"bytes,4,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterEdge) Reset() {
	*x = CharacterEdge{}
	mi := &file_media_character_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterEdge) ProtoMessage() {}

func (x *CharacterEdge) ProtoReflect() protoreflect.Message {
	mi := &file_media_character_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterEdge.ProtoReflect.Descriptor instead.
func (*CharacterEdge) Descriptor() ([]byte, []int) {
	return file_media_character_proto_rawDescGZIP(), []int{6}
}

func (x *CharacterEdge) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CharacterEdge) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CharacterEdge) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CharacterEdge) GetNode() *CharacterMin {
	if x != nil {
		return x.Node
	}
	return nil
}

type CharacterConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Edges         []*CharacterEdge       `protobuf:"bytes,1,rep,name=edges,proto3" json:"edges,omitempty"`
	PageInfo      *PageInfo              `protobuf:"bytes,2,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CharacterConnection) Reset() {
	*x = CharacterConnection{}
	mi := &file_media_character_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CharacterConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CharacterConnection) ProtoMessage() {}

func (x *CharacterConnection) ProtoReflect() protoreflect.Message {
	mi := &file_media_character_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CharacterConnection.ProtoReflect.Descriptor instead.
func (*CharacterConnection) Descriptor() ([]byte, []int) {
	return file_media_character_proto_rawDescGZIP(), []int{7}
}

func (x *CharacterConnection) GetEdges() []*CharacterEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *CharacterConnection) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

var File_media_character_proto protoreflect.FileDescriptor

const file_media_character_proto_rawDesc = "" +
	"\n" +
	"\x15media_character.proto\x12\tgoodanime\x1a\fcommon.proto\x1a\x0fmedia_min.proto\x1a\x11media_staff.proto\"\xdd\x01\n" +
	"\rCharacterName\x12\x12\n" +
	"\x04full\x18\x01 \x01(\tR\x04full\x12\x1b\n" +
	"\x06native\x18\x02 \x01(\tH\x00R\x06native\x88\x01\x01\x12*\n" +
	"\x0euser_preferred\x18\x03 \x01(\tH\x01R\ruserPreferred\x88\x01\x01\x12 \n" +
	"\valternative\x18\x04 \x03(\tR\valternative\x12/\n" +
	"\x13alternative_spoiler\x18\x05 \x03(\tR\x12alternativeSpoilerB\t\n" +
	"\a_nativeB\x11\n" +
	"\x0f_user_preferred\"]\n" +
	"\x0eCharacterImage\x12\x19\n" +
	"\x05large\x18\x01 \x01(\tH\x00R\x05large\x88\x01\x01\x12\x1b\n" +
	"\x06medium\x18\x02 \x01(\tH\x01R\x06medium\x88\x01\x01B\b\n" +
	"\x06_largeB\t\n" +
	"\a_medium\"}\n" +
	"\fCharacterMin\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12,\n" +
	"\x04name\x18\x02 \x01(\v2\x18.goodanime.CharacterNameR\x04name\x12/\n" +
	"\x05image\x18\x03 \x01(\v2\x19.goodanime.CharacterImageR\x05image\"\xb4\x01\n" +
	"\x12CharacterMediaEdge\x12*\n" +
	"\x0echaracter_role\x18\x01 \x01(\tH\x00R\rcharacterRole\x88\x01\x01\x12'\n" +
	"\x04node\x18\x02 \x01(\v2\x13.goodanime.MediaMinR\x04node\x126\n" +
	"\fvoice_actors\x18\x03 \x03(\v2\x13.goodanime.StaffMinR\vvoiceActorsB\x11\n" +
	"\x0f_character_role\"\x81\x01\n" +
	"\x18CharacterMediaConnection\x123\n" +
	"\x05edges\x18\x01 \x03(\v2\x1d.goodanime.CharacterMediaEdgeR\x05edges\x120\n" +
	"\tpage_info\x18\x02 \x01(\v2\x13.goodanime.PageInfoR\bpageInfo\"\x96\x05\n" +
	"\tCharacter\x12,\n" +
	"\x04name\x18\x01 \x01(\v2\x18.goodanime.CharacterNameR\x04name\x12/\n" +
	"\x05image\x18\x02 \x01(\v2\x19.goodanime.CharacterImageR\x05image\x12\x1b\n" +
	"\x06gender\x18\x03 \x01(\tH\x00R\x06gender\x88\x01\x01\x12\x15\n" +
	"\x03age\x18\x04 \x01(\tH\x01R\x03age\x88\x01\x01\x128\n" +
	"\rdate_of_birth\x18\x05 \x01(\v2\x14.goodanime.FuzzyDateR\vdateOfBirth\x12%\n" +
	"\vdescription\x18\x06 \x01(\tH\x02R\vdescription\x88\x01\x01\x12\x13\n" +
	"\x02id\x18\a \x01(\x05H\x03R\x02id\x88\x01\x01\x12\"\n" +
	"\n" +
	"blood_type\x18\b \x01(\tH\x04R\tbloodType\x88\x01\x01\x12#\n" +
	"\n" +
	"favourites\x18\t \x01(\x05H\x05R\n" +
	"favourites\x88\x01\x01\x12&\n" +
	"\fis_favourite\x18\n" +
	" \x01(\bH\x06R\visFavourite\x88\x01\x01\x12\x1e\n" +
	"\bsite_url\x18\v \x01(\tH\aR\asiteUrl\x88\x01\x01\x129\n" +
	"\x05media\x18\f \x01(\v2#.goodanime.CharacterMediaConnectionR\x05media\x125\n" +
	"\x14is_favourite_blocked\x18\r \x01(\bH\bR\x12isFavouriteBlocked\x88\x01\x01B\t\n" +
	"\a_genderB\x06\n" +
	"\x04_ageB\x0e\n" +
	"\f_descriptionB\x05\n" +
	"\x03_idB\r\n" +
	"\v_blood_typeB\r\n" +
	"\v_favouritesB\x0f\n" +
	"\r_is_favouriteB\v\n" +
	"\t_site_urlB\x17\n" +
	"\x15_is_favourite_blocked\"t\n" +
	"\rCharacterEdge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12+\n" +
	"\x04node\x18\x04 \x01(\v2\x17.goodanime.CharacterMinR\x04node\"w\n" +
	"\x13CharacterConnection\x12.\n" +
	"\x05edges\x18\x01 \x03(\v2\x18.goodanime.CharacterEdgeR\x05edges\x120\n" +
	"\tpage_info\x18\x02 \x01(\v2\x13.goodanime.PageInfoR\bpageInfoB\x19Z\x17goodanime/backend/protob\x06proto3"

var (
	file_media_character_proto_rawDescOnce sync.Once
	file_media_character_proto_rawDescData []byte
)

func file_media_character_proto_rawDescGZIP() []byte {
	file_media_character_proto_rawDescOnce.Do(func() {
		file_media_character_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_character_proto_rawDesc), len(file_media_character_proto_rawDesc)))
	})
	return file_media_character_proto_rawDescData
}

var file_media_character_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_media_character_proto_goTypes = []any{
	(*CharacterName)(nil),            // 0: goodanime.CharacterName
	(*CharacterImage)(nil),           // 1: goodanime.CharacterImage
	(*CharacterMin)(nil),             // 2: goodanime.CharacterMin
	(*CharacterMediaEdge)(nil),       // 3: goodanime.CharacterMediaEdge
	(*CharacterMediaConnection)(nil), // 4: goodanime.CharacterMediaConnection
	(*Character)(nil),                // 5: goodanime.Character
	(*CharacterEdge)(nil),            // 6: goodanime.CharacterEdge
	(*CharacterConnection)(nil),      // 7: goodanime.CharacterConnection
	(*MediaMin)(nil),                 // 8: goodanime.MediaMin
	(*StaffMin)(nil),                 // 9: goodanime.StaffMin
	(*PageInfo)(nil),                 // 10: goodanime.PageInfo
	(*FuzzyDate)(nil),                // 11: goodanime.FuzzyDate
}
var file_media_character_proto_depIdxs = []int32{
	0,  // 0: goodanime.CharacterMin.name:type_name -> goodanime.CharacterName
	1,  // 1: goodanime.CharacterMin.image:type_name -> goodanime.CharacterImage
	8,  // 2: goodanime.CharacterMediaEdge.node:type_name -> goodanime.MediaMin
	9,  // 3: goodanime.CharacterMediaEdge.voice_actors:type_name -> goodanime.StaffMin
	3,  // 4: goodanime.CharacterMediaConnection.edges:type_name -> goodanime.CharacterMediaEdge
	10, // 5: goodanime.CharacterMediaConnection.page_info:type_name -> goodanime.PageInfo
	0,  // 6: goodanime.Character.name:type_name -> goodanime.CharacterName
	1,  // 7: goodanime.Character.image:type_name -> goodanime.CharacterImage
	11, // 8: goodanime.Character.date_of_birth:type_name -> goodanime.FuzzyDate
	4,  // 9: goodanime.Character.media:type_name -> goodanime.CharacterMediaConnection
	2,  // 10: goodanime.CharacterEdge.node:type_name -> goodanime.CharacterMin
	6,  // 11: goodanime.CharacterConnection.edges:type_name -> goodanime.CharacterEdge
	10, // 12: goodanime.CharacterConnection.page_info:type_name -> goodanime.PageInfo
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_media_character_proto_init() }
func file_media_character_proto_init() {
	if File_media_character_proto != nil {
		return
	}
	file_common_proto_init()
	file_media_min_proto_init()
	file_media_staff_proto_init()
	file_media_character_proto_msgTypes[0].OneofWrappers = []any{}
	file_media_character_proto_msgTypes[1].OneofWrappers = []any{}
	file_media_character_proto_msgTypes[3].OneofWrappers = []any{}
	file_media_character_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_character_proto_rawDesc), len(file_media_character_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_media_character_proto_goTypes,
		DependencyIndexes: file_media_character_proto_depIdxs,
		MessageInfos:      file_media_character_proto_msgTypes,
	}.Build()
	File_media_character_proto = out.File
	file_media_character_proto_goTypes = nil
	file_media_character_proto_depIdxs = nil
}
