// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: media_review.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReviewUserRating int32

const (
	ReviewUserRating_REVIEW_USER_RATING_NO_VOTE_UNSPECIFIED ReviewUserRating = 0
	ReviewUserRating_REVIEW_USER_RATING_UP_VOTE             ReviewUserRating = 1
	ReviewUserRating_REVIEW_USER_RATING_DOWN_VOTE           ReviewUserRating = 2
)

// Enum value maps for ReviewUserRating.
var (
	ReviewUserRating_name = map[int32]string{
		0: "REVIEW_USER_RATING_NO_VOTE_UNSPECIFIED",
		1: "REVIEW_USER_RATING_UP_VOTE",
		2: "REVIEW_USER_RATING_DOWN_VOTE",
	}
	ReviewUserRating_value = map[string]int32{
		"REVIEW_USER_RATING_NO_VOTE_UNSPECIFIED": 0,
		"REVIEW_USER_RATING_UP_VOTE":             1,
		"REVIEW_USER_RATING_DOWN_VOTE":           2,
	}
)

func (x ReviewUserRating) Enum() *ReviewUserRating {
	p := new(ReviewUserRating)
	*p = x
	return p
}

func (x ReviewUserRating) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReviewUserRating) Descriptor() protoreflect.EnumDescriptor {
	return file_media_review_proto_enumTypes[0].Descriptor()
}

func (ReviewUserRating) Type() protoreflect.EnumType {
	return &file_media_review_proto_enumTypes[0]
}

func (x ReviewUserRating) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReviewUserRating.Descriptor instead.
func (ReviewUserRating) EnumDescriptor() ([]byte, []int) {
	return file_media_review_proto_rawDescGZIP(), []int{0}
}

type ReviewNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Score         int32                  `protobuf:"varint,2,opt,name=score,proto3" json:"score,omitempty"`
	Rating        int32                  `protobuf:"varint,3,opt,name=rating,proto3" json:"rating,omitempty"`
	RatingAmount  int32                  `protobuf:"varint,4,opt,name=rating_amount,json=ratingAmount,proto3" json:"rating_amount,omitempty"`
	Summary       string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	UserRating    ReviewUserRating       `protobuf:"varint,6,opt,name=user_rating,json=userRating,proto3,enum=goodanime.ReviewUserRating" json:"user_rating,omitempty"`
	User          *Viewer                `protobuf:"bytes,7,opt,name=user,proto3" json:"user,omitempty"`
	Body          string                 `protobuf:"bytes,8,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewNode) Reset() {
	*x = ReviewNode{}
	mi := &file_media_review_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewNode) ProtoMessage() {}

func (x *ReviewNode) ProtoReflect() protoreflect.Message {
	mi := &file_media_review_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewNode.ProtoReflect.Descriptor instead.
func (*ReviewNode) Descriptor() ([]byte, []int) {
	return file_media_review_proto_rawDescGZIP(), []int{0}
}

func (x *ReviewNode) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReviewNode) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ReviewNode) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *ReviewNode) GetRatingAmount() int32 {
	if x != nil {
		return x.RatingAmount
	}
	return 0
}

func (x *ReviewNode) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ReviewNode) GetUserRating() ReviewUserRating {
	if x != nil {
		return x.UserRating
	}
	return ReviewUserRating_REVIEW_USER_RATING_NO_VOTE_UNSPECIFIED
}

func (x *ReviewNode) GetUser() *Viewer {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ReviewNode) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type ReviewConnection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PageInfo      *PageInfo              `protobuf:"bytes,1,opt,name=page_info,json=pageInfo,proto3" json:"page_info,omitempty"`
	Nodes         []*ReviewNode          `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReviewConnection) Reset() {
	*x = ReviewConnection{}
	mi := &file_media_review_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewConnection) ProtoMessage() {}

func (x *ReviewConnection) ProtoReflect() protoreflect.Message {
	mi := &file_media_review_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewConnection.ProtoReflect.Descriptor instead.
func (*ReviewConnection) Descriptor() ([]byte, []int) {
	return file_media_review_proto_rawDescGZIP(), []int{1}
}

func (x *ReviewConnection) GetPageInfo() *PageInfo {
	if x != nil {
		return x.PageInfo
	}
	return nil
}

func (x *ReviewConnection) GetNodes() []*ReviewNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

var File_media_review_proto protoreflect.FileDescriptor

const file_media_review_proto_rawDesc = "" +
	"\n" +
	"\x12media_review.proto\x12\tgoodanime\x1a\fcommon.proto\x1a\fviewer.proto\"\x82\x02\n" +
	"\n" +
	"ReviewNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x05R\x05score\x12\x16\n" +
	"\x06rating\x18\x03 \x01(\x05R\x06rating\x12#\n" +
	"\rrating_amount\x18\x04 \x01(\x05R\fratingAmount\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12<\n" +
	"\vuser_rating\x18\x06 \x01(\x0e2\x1b.goodanime.ReviewUserRatingR\n" +
	"userRating\x12%\n" +
	"\x04user\x18\a \x01(\v2\x11.goodanime.ViewerR\x04user\x12\x12\n" +
	"\x04body\x18\b \x01(\tR\x04body\"q\n" +
	"\x10ReviewConnection\x120\n" +
	"\tpage_info\x18\x01 \x01(\v2\x13.goodanime.PageInfoR\bpageInfo\x12+\n" +
	"\x05nodes\x18\x02 \x03(\v2\x15.goodanime.ReviewNodeR\x05nodes*\x80\x01\n" +
	"\x10ReviewUserRating\x12*\n" +
	"&REVIEW_USER_RATING_NO_VOTE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aREVIEW_USER_RATING_UP_VOTE\x10\x01\x12 \n" +
	"\x1cREVIEW_USER_RATING_DOWN_VOTE\x10\x02B\x19Z\x17goodanime/backend/protob\x06proto3"

var (
	file_media_review_proto_rawDescOnce sync.Once
	file_media_review_proto_rawDescData []byte
)

func file_media_review_proto_rawDescGZIP() []byte {
	file_media_review_proto_rawDescOnce.Do(func() {
		file_media_review_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_review_proto_rawDesc), len(file_media_review_proto_rawDesc)))
	})
	return file_media_review_proto_rawDescData
}

var file_media_review_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_media_review_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_media_review_proto_goTypes = []any{
	(ReviewUserRating)(0),    // 0: goodanime.ReviewUserRating
	(*ReviewNode)(nil),       // 1: goodanime.ReviewNode
	(*ReviewConnection)(nil), // 2: goodanime.ReviewConnection
	(*Viewer)(nil),           // 3: goodanime.Viewer
	(*PageInfo)(nil),         // 4: goodanime.PageInfo
}
var file_media_review_proto_depIdxs = []int32{
	0, // 0: goodanime.ReviewNode.user_rating:type_name -> goodanime.ReviewUserRating
	3, // 1: goodanime.ReviewNode.user:type_name -> goodanime.Viewer
	4, // 2: goodanime.ReviewConnection.page_info:type_name -> goodanime.PageInfo
	1, // 3: goodanime.ReviewConnection.nodes:type_name -> goodanime.ReviewNode
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_media_review_proto_init() }
func file_media_review_proto_init() {
	if File_media_review_proto != nil {
		return
	}
	file_common_proto_init()
	file_viewer_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_review_proto_rawDesc), len(file_media_review_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_media_review_proto_goTypes,
		DependencyIndexes: file_media_review_proto_depIdxs,
		EnumInfos:         file_media_review_proto_enumTypes,
		MessageInfos:      file_media_review_proto_msgTypes,
	}.Build()
	File_media_review_proto = out.File
	file_media_review_proto_goTypes = nil
	file_media_review_proto_depIdxs = nil
}
