// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: media_list.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MediaListEntryWithMedia struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entry         *MediaListEntry        `protobuf:"bytes,1,opt,name=entry,proto3" json:"entry,omitempty"`
	Media         *MediaMin              `protobuf:"bytes,2,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaListEntryWithMedia) Reset() {
	*x = MediaListEntryWithMedia{}
	mi := &file_media_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaListEntryWithMedia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaListEntryWithMedia) ProtoMessage() {}

func (x *MediaListEntryWithMedia) ProtoReflect() protoreflect.Message {
	mi := &file_media_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaListEntryWithMedia.ProtoReflect.Descriptor instead.
func (*MediaListEntryWithMedia) Descriptor() ([]byte, []int) {
	return file_media_list_proto_rawDescGZIP(), []int{0}
}

func (x *MediaListEntryWithMedia) GetEntry() *MediaListEntry {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *MediaListEntryWithMedia) GetMedia() *MediaMin {
	if x != nil {
		return x.Media
	}
	return nil
}

type MediaListGroup struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Name          string                     `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Status        *MediaListStatus           `protobuf:"varint,2,opt,name=status,proto3,enum=goodanime.MediaListStatus,oneof" json:"status,omitempty"`
	Entries       []*MediaListEntryWithMedia `protobuf:"bytes,3,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaListGroup) Reset() {
	*x = MediaListGroup{}
	mi := &file_media_list_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaListGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaListGroup) ProtoMessage() {}

func (x *MediaListGroup) ProtoReflect() protoreflect.Message {
	mi := &file_media_list_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaListGroup.ProtoReflect.Descriptor instead.
func (*MediaListGroup) Descriptor() ([]byte, []int) {
	return file_media_list_proto_rawDescGZIP(), []int{1}
}

func (x *MediaListGroup) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MediaListGroup) GetStatus() MediaListStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return MediaListStatus_MEDIA_LIST_STATUS_UNSPECIFIED
}

func (x *MediaListGroup) GetEntries() []*MediaListEntryWithMedia {
	if x != nil {
		return x.Entries
	}
	return nil
}

type MediaListCollection struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasNextChunk  bool                   `protobuf:"varint,1,opt,name=has_next_chunk,json=hasNextChunk,proto3" json:"has_next_chunk,omitempty"`
	Lists         []*MediaListGroup      `protobuf:"bytes,2,rep,name=lists,proto3" json:"lists,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaListCollection) Reset() {
	*x = MediaListCollection{}
	mi := &file_media_list_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaListCollection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaListCollection) ProtoMessage() {}

func (x *MediaListCollection) ProtoReflect() protoreflect.Message {
	mi := &file_media_list_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaListCollection.ProtoReflect.Descriptor instead.
func (*MediaListCollection) Descriptor() ([]byte, []int) {
	return file_media_list_proto_rawDescGZIP(), []int{2}
}

func (x *MediaListCollection) GetHasNextChunk() bool {
	if x != nil {
		return x.HasNextChunk
	}
	return false
}

func (x *MediaListCollection) GetLists() []*MediaListGroup {
	if x != nil {
		return x.Lists
	}
	return nil
}

var File_media_list_proto protoreflect.FileDescriptor

const file_media_list_proto_rawDesc = "" +
	"\n" +
	"\x10media_list.proto\x12\tgoodanime\x1a\fcommon.proto\x1a\x16media_list_entry.proto\x1a\x0fmedia_min.proto\"u\n" +
	"\x17MediaListEntryWithMedia\x12/\n" +
	"\x05entry\x18\x01 \x01(\v2\x19.goodanime.MediaListEntryR\x05entry\x12)\n" +
	"\x05media\x18\x02 \x01(\v2\x13.goodanime.MediaMinR\x05media\"\xa6\x01\n" +
	"\x0eMediaListGroup\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x127\n" +
	"\x06status\x18\x02 \x01(\x0e2\x1a.goodanime.MediaListStatusH\x00R\x06status\x88\x01\x01\x12<\n" +
	"\aentries\x18\x03 \x03(\v2\".goodanime.MediaListEntryWithMediaR\aentriesB\t\n" +
	"\a_status\"l\n" +
	"\x13MediaListCollection\x12$\n" +
	"\x0ehas_next_chunk\x18\x01 \x01(\bR\fhasNextChunk\x12/\n" +
	"\x05lists\x18\x02 \x03(\v2\x19.goodanime.MediaListGroupR\x05listsB\x19Z\x17goodanime/backend/protob\x06proto3"

var (
	file_media_list_proto_rawDescOnce sync.Once
	file_media_list_proto_rawDescData []byte
)

func file_media_list_proto_rawDescGZIP() []byte {
	file_media_list_proto_rawDescOnce.Do(func() {
		file_media_list_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_list_proto_rawDesc), len(file_media_list_proto_rawDesc)))
	})
	return file_media_list_proto_rawDescData
}

var file_media_list_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_media_list_proto_goTypes = []any{
	(*MediaListEntryWithMedia)(nil), // 0: goodanime.MediaListEntryWithMedia
	(*MediaListGroup)(nil),          // 1: goodanime.MediaListGroup
	(*MediaListCollection)(nil),     // 2: goodanime.MediaListCollection
	(*MediaListEntry)(nil),          // 3: goodanime.MediaListEntry
	(*MediaMin)(nil),                // 4: goodanime.MediaMin
	(MediaListStatus)(0),            // 5: goodanime.MediaListStatus
}
var file_media_list_proto_depIdxs = []int32{
	3, // 0: goodanime.MediaListEntryWithMedia.entry:type_name -> goodanime.MediaListEntry
	4, // 1: goodanime.MediaListEntryWithMedia.media:type_name -> goodanime.MediaMin
	5, // 2: goodanime.MediaListGroup.status:type_name -> goodanime.MediaListStatus
	0, // 3: goodanime.MediaListGroup.entries:type_name -> goodanime.MediaListEntryWithMedia
	1, // 4: goodanime.MediaListCollection.lists:type_name -> goodanime.MediaListGroup
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_media_list_proto_init() }
func file_media_list_proto_init() {
	if File_media_list_proto != nil {
		return
	}
	file_common_proto_init()
	file_media_list_entry_proto_init()
	file_media_min_proto_init()
	file_media_list_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_list_proto_rawDesc), len(file_media_list_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_media_list_proto_goTypes,
		DependencyIndexes: file_media_list_proto_depIdxs,
		MessageInfos:      file_media_list_proto_msgTypes,
	}.Build()
	File_media_list_proto = out.File
	file_media_list_proto_goTypes = nil
	file_media_list_proto_depIdxs = nil
}
