// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: viewer.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ViewerAvatar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Medium        string                 `protobuf:"bytes,1,opt,name=medium,proto3" json:"medium,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ViewerAvatar) Reset() {
	*x = ViewerAvatar{}
	mi := &file_viewer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ViewerAvatar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewerAvatar) ProtoMessage() {}

func (x *ViewerAvatar) ProtoReflect() protoreflect.Message {
	mi := &file_viewer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewerAvatar.ProtoReflect.Descriptor instead.
func (*ViewerAvatar) Descriptor() ([]byte, []int) {
	return file_viewer_proto_rawDescGZIP(), []int{0}
}

func (x *ViewerAvatar) GetMedium() string {
	if x != nil {
		return x.Medium
	}
	return ""
}

type Viewer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CreatedAt     int32                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Avatar        *ViewerAvatar          `protobuf:"bytes,4,opt,name=avatar,proto3" json:"avatar,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Viewer) Reset() {
	*x = Viewer{}
	mi := &file_viewer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Viewer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Viewer) ProtoMessage() {}

func (x *Viewer) ProtoReflect() protoreflect.Message {
	mi := &file_viewer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Viewer.ProtoReflect.Descriptor instead.
func (*Viewer) Descriptor() ([]byte, []int) {
	return file_viewer_proto_rawDescGZIP(), []int{1}
}

func (x *Viewer) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Viewer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Viewer) GetCreatedAt() int32 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Viewer) GetAvatar() *ViewerAvatar {
	if x != nil {
		return x.Avatar
	}
	return nil
}

var File_viewer_proto protoreflect.FileDescriptor

const file_viewer_proto_rawDesc = "" +
	"\n" +
	"\fviewer.proto\x12\tgoodanime\"&\n" +
	"\fViewerAvatar\x12\x16\n" +
	"\x06medium\x18\x01 \x01(\tR\x06medium\"|\n" +
	"\x06Viewer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x05R\tcreatedAt\x12/\n" +
	"\x06avatar\x18\x04 \x01(\v2\x17.goodanime.ViewerAvatarR\x06avatarB\x19Z\x17goodanime/backend/protob\x06proto3"

var (
	file_viewer_proto_rawDescOnce sync.Once
	file_viewer_proto_rawDescData []byte
)

func file_viewer_proto_rawDescGZIP() []byte {
	file_viewer_proto_rawDescOnce.Do(func() {
		file_viewer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_viewer_proto_rawDesc), len(file_viewer_proto_rawDesc)))
	})
	return file_viewer_proto_rawDescData
}

var file_viewer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_viewer_proto_goTypes = []any{
	(*ViewerAvatar)(nil), // 0: goodanime.ViewerAvatar
	(*Viewer)(nil),       // 1: goodanime.Viewer
}
var file_viewer_proto_depIdxs = []int32{
	0, // 0: goodanime.Viewer.avatar:type_name -> goodanime.ViewerAvatar
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_viewer_proto_init() }
func file_viewer_proto_init() {
	if File_viewer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_viewer_proto_rawDesc), len(file_viewer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_viewer_proto_goTypes,
		DependencyIndexes: file_viewer_proto_depIdxs,
		MessageInfos:      file_viewer_proto_msgTypes,
	}.Build()
	File_viewer_proto = out.File
	file_viewer_proto_goTypes = nil
	file_viewer_proto_depIdxs = nil
}
