query Media($mediaId: Int, $notYetAired: Boolean) {
  Media(id: $mediaId) {
    id
    bannerImage
    nextAiringEpisode {
      airingAt
      episode
      timeUntilAiring
    }
    ...mediaFullFields
    airingSchedule(notYetAired: $notYetAired) {
      pageInfo { ...pageInfoFields }
      edges {
        id
        node {
          airingAt
          episode
          id
          mediaId
          timeUntilAiring
        }
      }
    }
    mediaListEntry {
      mediaId
      progress
      repeat
      score(format: POINT_10_DECIMAL)
      startedAt { ...fuzzyDateFields }
      completedAt { ...fuzzyDateFields }
      status
      private
    }
    nextAiringEpisode {
      airingAt
      episode
      timeUntilAiring
      mediaId
    }
    rankings {
      allTime
      context
      format
      id
      rank
      season
      type
      year
    }
    externalLinks {
      color
      icon
      id
      isDisabled
      language
      notes
      site
      siteId
      type
      url
    }
    studios {
      edges {
        isMain
        node {
          id
          name
          siteUrl
        }
      }
      pageInfo { ...pageInfoFields }
    }
    streamingEpisodes {
      site
      thumbnail
      title
      url
    }
    tags {
      category
      id
      isAdult
      isGeneralSpoiler
      isMediaSpoiler
      name
      rank
    }
    stats {
      scoreDistribution {
        amount
        score
      }
      statusDistribution {
        status
        amount
      }
    }
    trends {
      pageInfo { ...pageInfoFields }
      edges {
        node {
          averageScore
          episode
          inProgress
          popularity
          releasing
          trending
          date
        }
      }
    }
    characters(page: 1, perPage: 25, sort: [RELEVANCE]) {
      pageInfo { ...pageInfoFields }
      edges {
        id
        role
        voiceActors(sort: [RELEVANCE]) {
          image {
            large
            medium
          }
          name {
            full
          }
          languageV2
        }
        node {
          name {
            full
            native
            alternative
            alternativeSpoiler
            userPreferred
          }
          image {
            large
            medium
          }
        }
      }
    }
    staff(page: 1, perPage: 25, sort: [RELEVANCE]) {
      pageInfo { ...pageInfoFields }
      edges {
        role
        node {
          name {
            userPreferred
            full
            native
          }
          image {
            large
            medium
          }
        }
      }
    }
    relations {
      edges {
        relationType
        node {
          id
          title { ...titleFields }
          coverImage { ...coverImageFields }
          format
        }
      }
    }
  }
}

fragment titleFields on MediaTitle {
  english
  native
  romaji
  userPreferred
}

fragment coverImageFields on MediaCoverImage {
  color
  extraLarge
  large
  medium
}

fragment pageInfoFields on PageInfo {
  hasNextPage
  currentPage
}

fragment fuzzyDateFields on FuzzyDate {
  day
  month
  year
}


fragment mediaFullFields on Media {
  id
  idMal
  title { ...titleFields }
  coverImage { ...coverImageFields }
  bannerImage
  description(asHtml: true)
  format
  status
  episodes
  chapters
  volumes
  duration
  season
  seasonYear
  averageScore
  meanScore
  popularity
  favourites
  source
  hashtag
  countryOfOrigin
  isAdult
  isFavourite
  isFavouriteBlocked
  isLicensed
  isLocked
  isRecommendationBlocked
  isReviewBlocked
  startDate { ...fuzzyDateFields }
  endDate { ...fuzzyDateFields }
  trailer {
    id
    site
    thumbnail
  }
  siteUrl
  trending
  type
  genres
  synonyms
}
