query MediaList($userId: Int, $type: MediaType, $sort: [MediaListSort]) {
    MediaListCollection(userId: $userId, type: $type, sort: $sort) {
        hasNextChunk
        lists {
            name
            status
            entries {
                id
                media {
                    id
                    averageScore
                    episodes
                    format
                    isAdult
                    isFavourite
                    siteUrl
                    title {
                        english
                        native
                        romaji
                        userPreferred
                    }
                    coverImage {
                        color
                        medium
                        large
                        extraLarge
                    }
                }
                progress
                repeat
                status
                score(format: POINT_10_DECIMAL)
                startedAt {
                    day
                    month
                    year
                }
                completedAt {
                    day
                    month
                    year
                }
            }
        }
    }
}
