query MediaList($userId: Int, $type: MediaType, $sort: [MediaListSort]) {
    MediaListCollection(userId: $userId, type: $type, sort: $sort) {
        hasNextChunk
        lists {
            name
            status
            entries {
                id
                media {
                    id
                    title {
                        userPreferred
                    }
                    averageScore
                    coverImage {
                        large
                        color
                    }
                    episodes
                    format
                    isAdult
                    isFavourite
                }
                progress
                repeat
                status
                score
                startedAt {
                    day
                    month
                    year
                }
                completedAt {
                    day
                    month
                    year
                }
            }
        }
    }
}
