query Media($mediaId: Int, $page: Int, $perPage: Int) {
    Media(id: $mediaId) {
        id
        recommendations(page: $page, perPage: $perPage, sort: [RATING_DESC]) {
            pageInfo {
                hasNextPage
                currentPage
            }
            edges {
                node {
                    rating
                    mediaRecommendation {
                        id
                        type
                        averageScore
                        episodes
                        chapters
                        volumes
                        format
                        isAdult
                        isFavourite
                        siteUrl
                        seasonYear
                        title {
                            english
                            native
                            romaji
                            userPreferred
                        }
                        coverImage {
                            color
                            medium
                            large
                            extraLarge
                        }
                    }
                }
            }
        }
    }
}
