query Media($mediaId: Int, $page: Int, $perPage: Int) {
    Media(id: $mediaId) {
        id
        characters(page: $page, perPage: $perPage, sort: [RELEVANCE]) {
            pageInfo {
                hasNextPage
                currentPage
            }
            edges {
                id
                role
                name
                voiceActors(sort: [RELEVANCE]) {
                    image {
                        large
                        medium
                    }
                    name {
                        full
                    }
                    languageV2
                }
                node {
                    name {
                        full
                        native
                        alternative
                        alternativeSpoiler
                        userPreferred
                    }
                    age
                    gender
                    dateOfBirth {
                        day
                        month
                        year
                    }
                    description(asHtml: true)
                    image {
                        large
                        medium
                    }
                }
            }
        }
    }
}
