mutation SaveMediaListEntry(
    $mediaId: Int
    $progress: Int
    $progressVolumes: Int
    $status: MediaListStatus
    $startedAt: FuzzyDateInput
    $completedAt: FuzzyDateInput
    $score: Float
    $repeat: Int
) {
    SaveMediaListEntry(
        mediaId: $mediaId
        progress: $progress
        progressVolumes: $progressVolumes
        repeat: $repeat
        status: $status
        startedAt: $startedAt
        completedAt: $completedAt
        score: $score
    ) {
        id
        status
        progress
        progressVolumes
        score(format: POINT_10_DECIMAL)
        repeat
        startedAt {
            day
            month
            year
        }
        completedAt {
            day
            month
            year
        }
    }
}
