syntax = "proto3";

package goodanime;

import "common.proto";
import "media.proto";
import "media_activity.proto";
import "media_list.proto";
import "media_list_entry.proto";
import "media_min.proto";
import "media_misc.proto";
import "media_review.proto";
import "media_staff.proto";
import "media_studio.proto";
import "viewer.proto";

option go_package = "goodanime/backend/proto";

message FetchMediaListRequest {
  int32 user_id = 1;
  string type = 2;
  repeated string sort = 3;
}

message FetchMediaListResponse {
  MediaListCollection collection = 1;
  string error = 2;
}

message FetchViewerResponse {
  Viewer viewer = 1;
  string error = 2;
}

message FuzzyDateInput {
  optional int32 year = 1;
  optional int32 month = 2;
  optional int32 day = 3;
}

message SaveMediaListEntryRequest {
  int32 media_id = 1;
  optional int32 progress = 2;
  optional string status = 3;
  optional double score = 4;
  optional FuzzyDateInput started_at = 5;
  optional FuzzyDateInput completed_at = 6;
  optional int32 progress_volumes = 7;
  optional int32 repeat = 8;
}

message SaveMediaListEntryResponse {
  MediaListEntry entry = 1;
  string error = 2;
}

message FetchMediaDetailsRequest {
  int32 media_id = 1;
}

message FetchMediaDetailsResponse {
  Media media = 1;
  string error = 2;
}

message FetchMediaStaffRequest {
  int32 media_id = 1;
  int32 page = 2;
  int32 per_page = 3;
}

message FetchMediaStaffResponse {
  Media media = 1;
  string error = 2;
}

message FetchMediaCharactersRequest {
  int32 media_id = 1;
  int32 page = 2;
  int32 per_page = 3;
}

message FetchMediaCharactersResponse {
  Media media = 1;
  string error = 2;
}

message FetchMediaRecommendationsRequest {
  int32 media_id = 1;
  int32 page = 2;
  int32 per_page = 3;
}

message FetchMediaRecommendationsResponse {
  Media media = 1;
  string error = 2;
}

message ToggleFavouriteAnimeRequest {
  int32 anime_id = 1;
}

message ToggleFavouriteAnimeResponse {
  int32 anime_id = 1;
  bool is_favourite = 2;
  string error = 3;
}

message ToggleFavouriteMangaRequest {
  int32 manga_id = 1;
}

message ToggleFavouriteMangaResponse {
  int32 manga_id = 1;
  bool is_favourite = 2;
  string error = 3;
}

message ToggleActivityLikeRequest {
  int32 activity_id = 1;
}

message ToggleActivityLikeResponse {
  int32 activity_id = 1;
  repeated int32 liked_user_ids = 2;
  string error = 3;
}

message DeleteMediaListEntryRequest {
  int32 entry_id = 1;
}

message DeleteMediaListEntryResponse {
  int32 entry_id = 1;
  bool deleted = 2;
  string error = 3;
}

message FetchMediaReviewsRequest {
  int32 media_id = 1;
  int32 page = 2;
  int32 per_page = 3;
}

message FetchMediaReviewsResponse {
  Media media = 1;
  string error = 2;
}

message RateReviewRequest {
  int32 review_id = 1;
  ReviewUserRating rating = 2;
}

message RateReviewResponse {
  ReviewNode review = 1;
  string error = 2;
}

message FetchMediaActivitiesRequest {
  int32 media_id = 1;
  int32 page = 2;
  int32 per_page = 3;
}

message FetchMediaActivitiesResponse {
  PageInfo page_info = 1;
  repeated ListActivity activities = 2;
  string error = 3;
}

message FetchStudioDetailsRequest {
  int32 studio_id = 1;
  int32 page = 2;
}

message FetchStudioDetailsResponse {
  Studio studio = 1;
  string error = 2;
}

message ToggleFavouriteStudioRequest {
  int32 studio_id = 1;
}

message ToggleFavouriteStudioResponse {
  int32 studio_id = 1;
  string error = 2;
}

message FetchStaffDetailsRequest {
  int32 staff_id = 1;
  int32 character_media_page = 2;
  int32 staff_media_page = 3;
}

message FetchStaffDetailsResponse {
  Staff staff = 1;
  string error = 2;
}

message ToggleFavouriteStaffRequest {
  int32 staff_id = 1;
}

message ToggleFavouriteStaffResponse {
  int32 staff_id = 1;
  string error = 2;
}

message FetchGenresResponse {
  repeated string genres = 1;
  string error = 2;
}

message FetchTagsResponse {
  repeated MediaTag tags = 1;
  string error = 2;
}

message FetchMediaSearchRequest {
  int32 page = 1;
  optional string query = 2;
  repeated string sort = 3;
  optional string type = 4;
  optional string format = 5;
  optional string format_not = 6;
  repeated string format_in = 7;
  repeated string format_not_in = 8;
  optional string status = 9;
  optional bool on_list = 10;
  optional int32 min_average_score = 11;
  optional int32 max_average_score = 12;
  optional int32 average_score = 13;
  optional string season = 14;
  optional int32 start_date = 15;
  optional int32 min_start_date = 16;
  optional int32 max_start_date = 17;
  optional int32 episodes = 18;
  optional int32 min_episodes = 19;
  optional int32 max_episodes = 20;
  optional int32 duration = 21;
  optional int32 min_duration = 22;
  optional int32 max_duration = 23;
  optional int32 chapters = 24;
  optional int32 min_chapters = 25;
  optional int32 max_chapters = 26;
  optional int32 volumes = 27;
  optional int32 min_volumes = 28;
  optional int32 max_volumes = 29;
  optional bool is_adult = 30;
  repeated string genre_in = 31;
  repeated string genre_not_in = 32;
  repeated string tag_in = 33;
  repeated string tag_not_in = 34;
  optional int32 minimum_tag_rank = 35;
}

message FetchMediaSearchResponse {
  repeated MediaMin media = 1;
  PageInfo page_info = 2;
  string error = 3;
}

message FetchStudioSearchRequest {
  int32 page = 1;
  optional string query = 2;
  repeated string sort = 3;
}

message FetchStudioSearchResponse {
  repeated Studio studios = 1;
  PageInfo page_info = 2;
  string error = 3;
}
