syntax = "proto3";

package goodanime;

import "media_character.proto";
import "media_edge.proto";
import "media_list_entry.proto";
import "media_min.proto";
import "media_misc.proto";
import "media_recommendation.proto";
import "media_review.proto";
import "media_staff.proto";
import "media_studio.proto";
import "media_trend.proto";

option go_package = "goodanime/backend/proto";

message Media {
  MediaMin base = 1;
  string description = 2;
  string banner_image = 3;
  string status = 4;
  repeated string genres = 5;
  int32 popularity = 6;
  string season = 7;
  Trailer trailer = 9;
  MediaListEntry media_list_entry = 10;
  StudioConnection studios = 11;
  repeated MediaTag tags = 12;
  repeated ExternalLink external_links = 13;
  repeated StreamingEpisode streaming_episodes = 14;
  StaffConnection staff = 15;
  AiringSchedule next_airing_episode = 16;
  CharacterConnection characters = 17;
  MediaConnection relations = 18;
  RecommendationConnection recommendations = 19;
  repeated MediaRank rankings = 20;
  MediaStats stats = 21;
  MediaTrendConnection trends = 22;
  optional int32 mean_score = 23;
  optional int32 favourites = 24;
  repeated string synonyms = 25;
  ReviewConnection reviews = 26;
}
